api/Dataservices/DevicePinDataservice.cs

- 輸出 pin 資料的時候加上 mode 欄位, 此欄位包含兩個值一個是 0 是 SWITCH, 1 是 SENSOR
- API
透過 post man 打以下 API (記得要登入)
https://dev.itemhub.io:5001/api/v1/me/devices/57/pins
檢查格式是否如下
```json
[
{
"pin": "D0",
"deviceId": 57,
"mode": 1
}
]
```

fix: 加上 Device Pin mode 到 api 上面 (sensor/switch)

---

api/Constants/TriggerOperator.cs
api/Controllers/UniversalController.cs

- Ref #249
- as Title 
- API
https://localhost:5001/swagger/index.html
IotUniversal Section 試著打開 trigger-operators 用 swagger UI 打這個 api 
預期拿到的資料格式長這樣
```json
[
{
"key": "B",
"value": 0,
"label": "大於"
},
{
"key": "BE",
"value": 1,
"label": "大於等於"
}
]
```

feat api: 把 api trigger operators 輸出給 client 使用

---

api/Controllers/MyOauthClientController.cs
api/Dataservices/OauthClientDataservice.cs

- oAuth Clients 是給裝置登入的帳號密碼, 使用者無法修改密碼只能送出重新產生密碼的需求, 避免使用者用太過簡易或是有特殊意義的密碼
- API
先登入, 用 postman 打 `/api/v1/oauth-clients/:id/revoke-secrets`  `POST` 看一下回應訊息是否符合以下格式
```json
{
secret: "...................................."
}
```

feat: 實作重新產生 oAuth Clients 密碼 api

---

website/src/controllers/oauth.controller.js

- 如標題
- Website F2E
在 local 端測試看一下彈出的 oAuth window 是否會被關掉還是會卡在那邊跳出一個錯誤訊息, 正常情況會自動關掉視窗

fix: 修正 opener.gtag  呼叫造成  error, gtag 應該是定義在 opener.window 上

---

README.md
api/Controllers/MyDeviceController.cs
api/Controllers/MyOauthClientController.cs
api/Controllers/MyOauthClientRedirectUriController.cs
api/Controllers/MyTriggerController.cs
api/Controllers/MyZoneController.cs
api/Controllers/UserController.cs
api/Homo.AuthApi/Controllers/GroupController.cs
api/Homo.AuthApi/Controllers/UserController.cs
api/Homo.AuthApi/Dataservices/UserDataservice.cs
api/Homo.AuthApi/tools/auto-generator/template/controller.cs.template
dashboard/src/components/pagination/pagination.tsx
dashboard/src/constants/api.ts
dashboard/src/dataservices/devices.dataservice.ts
dashboard/src/hooks/apis/devices.hook.ts
dashboard/src/hooks/apis/oauth-clients.hook.ts
dashboard/src/hooks/apis/triggers.hook.ts
dashboard/src/pages/device/device.tsx
dashboard/src/pages/oauth-clients/oauth-clients.tsx
dashboard/src/pages/trigger/trigger.module.scss
dashboard/src/pages/trigger/trigger.tsx
dashboard/src/pages/triggers/triggers.module.scss
dashboard/src/pages/triggers/triggers.tsx
dashboard/src/redux/reducers/devices.reducer.ts
dashboard/src/redux/reducers/oauth-clients.reducer.ts
dashboard/src/redux/reducers/triggers.reducer.ts
dashboard/src/redux/store.ts
dashboard/src/types/dataservices.type.ts
dashboard/src/types/response.type.ts
dashboard/src/types/triggers.type.ts

https://github.com/miterfrants/itemhub/issues/248 中的部分 Tasks
- 串接 GET triggers api、DELETE triggers api，實作 triggers 的 reducer、hook。
- 渲染 triggers 頁面，並有 pagination (取共用元件)。
- 渲染 trigger 頁面。
- API (只有修改 key 命名，對齊 olient-clients)
- 進入 triggers / trigger page 會顯示 id / ownerId / source device name / source device pin / destination device name / destination device pin 相關資訊。
@miterfrants @vickychou99 
- DELETE 前可以跳個 Modal，做些確認動作，確保沒刪錯
- GET single trigger API
- CUD 的操作

Feat: implement simple triggers / triger page

---

dashboard/src/hooks/apis/oauth-clients.hook.ts
dashboard/src/pages/oauth-client/oauth-client.tsx
dashboard/src/pages/oauth-clients/oauth-clients.tsx
dashboard/src/redux/reducers/oauth-clients.reducer.ts

- 讓 outh-clients 的 page 來源只有從 query.page 來，而不會有內部 page state，統一資料來源
- 讓 outh-clients 的 rowNum 來源只有從 redux store 來，藉此統一 list api 資料來源皆由 store 來
p.s. 前面的兩個 pr merge 後，這個應該會有小衝突，我會再解掉
- oauth-clients 頁面的 pagination 資料正常顯示與運作
@miterfrants @vickychou99

Refactor: refactor outh-clients rowNum and page state source

---

api/Controllers/MyDeviceController.cs
api/Dataservices/DeviceActivityLogDataservice.cs
api/Models/EF/DeviceActivityLog.cs
api/Models/EF/IotDbContext.cs
api/Services/TimeoutOfflineDeviceService.cs

- Ref #292 
- 把裝置下線機制改成可以運作在多台 api server 狀況, 實作的原理: 把裝置活動的紀錄放在資料庫, 每一次裝置打一次 device online api 就會觸發計時器, 到這裡都跟舊的機制一樣, 不一樣在倒數計時器時間到了以後的 callback func 會去檢查裝置活動紀錄最後一次的時間在什麼時候, 如果發現 15 秒內都沒有任何活動就把狀態切成 offline
- API
- 打 `POST` `https://localhost:5001/api/v1/me/devices/56/online` 
- 檢查 56 device status 是否變成 1 
- 檢查 db DeviceActivityLog 是否多新增一筆剛剛的紀錄
- 15 秒後看一下 56 device status 是否變成 0

feat: 把下線機制改成可以運作在多台 api server

---

dashboard/src/redux/reducers/oauth-clients.reducer.ts

發到 master hotfix。
https://github.com/miterfrants/itemhub/issues/303
- 根本原因在於 `oauthClientsSlice` 中的 `refreshOne`，並沒有把打完 API 接收的 oauthClients，正確 set 進去，導致 oauthClients 永遠是 null，進而再次觸發打 API 拿資料，造成無限循環。
- 進入這個網址 [http://localhost:3000/dashboard/oauth-clients/27](http://localhost:3000/dashboard/oauth-clients/27)，重新整理頁面，不會再重複打 API 
@miterfrants  @vickychou99

hotfix: fix-oauth-client-render-loop-bug (to master)

---

api/Homo.AuthApi/Filters/AuthorizeAttribute.cs

- 認證 Filter 取得使用者 ID 的 function 是固定拿 Cookie 中名稱為 token 的資料, 但這時候的 key 已經換成 dashbaordJwtKey 所以會發生驗證錯誤解不開 jwt 的問題
- API
- 取得兩階段驗證, 到了 http://localhost:3000/dashboard/devices/ 看一下是否可以正常顯示列表

fix: 修正 Dashboard 沒辦法正常取得 API 資料

---

api/Homo.AuthApi/Constants/Error.cs
api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
api/Localization/Error/zh-TW.json

- Ref #329
- API
- 跑一次註冊驗證信流程, 使用已經註冊使用者 email 
@LiangYingC

fix: 避免已經註冊的 email 再發送驗證信件

---

api/Dataservices/DevicePinSensorDataservice.cs
api/Helpers/Subscription.Helper.cs
api/Services/ClearExpiredDevicePinSensorDataCronJobService.cs
api/Startup.cs

- Ref #326 
- as title
- API
- 先確認一下自己帳號所訂閱的方案, 確定資料保存時間
- 資料庫把 DeviceSensorData 複製一些資料, 並把資料的 OwnerId 改成自己, 修改 CreatedAt 把時間改在訂閱方案時刻前後
- 把 Startup.cs 
```
services.AddCronJob<ClearExpiredDevicePinSensorDataCronJobService>(c =>
{
c.TimeZoneInfo = TimeZoneInfo.Local;
c.CronExpression = @"0 0 * * *";
});
```
其中的 `0 0 * * *` 改成 `* * * * *` 每分鐘執行
- 跑完後檢查一下資料庫 DeviceSensorData 是否訂閱方案時刻前的資料被留著, 過期的資料被刪掉

feat: 實作依照使用者訂閱方案清除資料

---

api/Constants/Error.cs
api/Controllers/MyOauthClientController.cs
api/Dataservices/OauthClientDataservice.cs
api/Localization/Error/zh-TW.json
api/Models/DTOs/OauthClient.cs

- as title
- API
- 試著打 `v1/my/oauth-clients` POST 不傳任何參數是否可以正常建立
- 同上一個 API 位置, 相同 deviceId 看是否在新增第二次會發生錯誤提醒

feat: oauth-client 修改成允許使用者傳空的 clientId 和避免同一個 deviceId 有多個 client

---

dashboard/src/css/button.scss
dashboard/src/css/tag.scss

- 修正按鈕斷行問題
- 修正裝置狀態斷行問題
- 按鈕斷行可以參考上面圖片
- 裝置狀態斷行需要用手機連到或是等上了測試機再測試

 fix: 修正按鈕和 tag 斷行

---

dashboard/src/app.tsx
dashboard/src/components/footer/footer.tsx
dashboard/src/components/header/header.tsx
dashboard/src/components/page-title/page-title.tsx
dashboard/src/pages/dashboard/dashboard.scss
dashboard/src/redux/reducers/menu.reducer.ts

- 修正 page-title component 在比較小尺寸上的斷行
- UX 小尺寸的螢幕再切換連結的時候會把 menu 收起來
- 把畫面縮小到 <=767 展開選單, 切換連結看一下是否選單會自動縮起來
- 切到 http://localhost:3000/dashboard/oauth-clients 看一下按鈕是否有放在不同列顯示 e.g

refactor: 修正 page-title component 在比較小尺寸上的斷行

---

dashboard/src/hooks/apis/fetch.hook.ts
dashboard/src/redux/reducers/triggers.reducer.ts

目前看來 `useFetchApi` 中，某些情況下，callback 執行完畢後，就會 return，不會繼續執行到  `setData/setHttpsetHttpStatus`，順序有點不對，應該是要先執行 `setData/setHttpsetHttpStatus` 才執行 callback 才合理。
- 確保 `setData/setHttpsetHttpStatus` 一定會執行到，不會因為 callback 的任何作用而被阻擋
```
const { isUpdatingTrigger, updateTriggerApi, updateTriggerResponse } =
useUpdateTriggerApi({
trigerId: trigger?.id || 0,
updatedData: {
...editedTriggerData,
sourceThreshold: Number(editedTriggerData.sourceThreshold),
},
});
```
update trigger 成功後，`updateTriggerResponse` 會回傳 {status:ok}
@miterfrants  @vickychou99

fix: make sure will setData/setHttpStatus before callbackfunc executed

---

api/Homo.AuthApi/Models/EF/DBContext.cs
api/Migrations/DB/20220606083649_IsDeletedEmailUniqueIndex.Designer.cs
api/Migrations/DB/20220606083649_IsDeletedEmailUniqueIndex.cs

- as title
- API
- 把某個特定的使用者刪除後 在 DB.User.DeletedAt 加上 NOW()
- 在重新註冊一個使用者, 在 Email 驗證看是否還會出現重複的 Email 

fix: 修正如果已經刪除的使用者, 他的 email 還是會被判斷為重複註冊

---

dashboard/src/components/pins/pins.tsx

- 每一次到 pins.tsx 都去拿資料避免在別的地方只拿到部分資料這邊就會留空
- http://localhost:3000/  dashboard 頁面拿部分 device pins 
- http://localhost:3000/dashboard/devices 檢查是否所有 device pins 都有顯示

fix: 修正 device 列表 device pin 空白

---

dashboard/src/components/pin/pin.tsx

- Ref:#975
- 修改 setIsInitialized = true 的判斷， BUG 是因為 setValue 還沒執行完成時，就先執行 setIsInitialized 了，導致 value 更新後又打一次 patch api 
- 確認進 Device 列表頁 / 明細頁，不會打 Patch API
- 確認 Switch 的狀態於 列頁表 / 明細頁，可以正常切換開關

feat: 修正一進 Device 列表頁就打 Patch API

---

api/Services/AutoPaymentCronJobService.cs
api/Services/ClearExpiredDevicePinSensorDataCronJobService.cs
api/Services/CronJobService.cs
api/Services/DeviceActivityLogCronJobService.cs
api/Services/SendOverPlanNotificationCronJobService.cs
api/Services/TriggerLogCronJobService.cs

- #1016 
- 執行`new System.Timers.Timer(delay.TotalMilliseconds);` 時， `delay.TotalMilliseconds` 傳入負數而產生錯誤。
- cronjob 計時器可能因為時間校正的關係，而讓執行 cronjob 的時間小於 Now，因此 `delay.TotalMilliseconds` 小於 0
- 此時程式雖然會重新排程，但因原本的 Schedule Function 內算出來的 `delay.TotalMilliseconds` 依然是小於 0 ，因此產生 bug 。
- 將執行計時器的程式改於 `delay.TotalMilliseconds > 0` 時執行即可。
- API
- 確認 cronjob 正常運作

feat: 修正 cronjob 計時器

---

api/Services/TimeoutOfflineDeviceService.cs

- as title
- #1019
- API
- 透過 postman 打 `POST` `"{id}/online"` API
- 看 16 秒後是否有下線 (本來 reset timer 是 16 秒)，現在改成 60 秒

feat: 延長檢查裝置下線的時間

---

dashboard/src/components/custom-pipeline-item/schedule-pipeline-item.tsx

- 修正 Cron Expression 的連結改為 wiki 的不要用 IBM 的版本，因為 IBM 的版本有秒數會誤導使用者
- https://itemhub.io/dashboard/pipelines/{id}
- 新增一個 pipeline 然後加入排成看一下連結是否連到 wiki

fix: update cron expression link

---

api/Dataservices/DevicePinDataservice.cs

- 已經刪除的裝置不要再顯示在 Google Smart Home 的 Device List
- API
`{{endpoint}}/api/v1/google-smart-home` 
```
{
"inputs": [
{
"intent": "action.devices.SYNC"
}
],
"requestId": "16080306685035390925"
}
```

fix: 修正已經刪除的 device 不要出現在 google smart home query 裏頭

---

api/Controllers/MyDevicePinSwitchController.cs
api/Controllers/OauthController.cs
api/Homo.AuthApi/Models/DTOs/JwtExtraPayload.cs

- exchange-token-for-device api 多給一個 flag 讓 server 知道這個 token 是否來自於 Device 如果是的話在拿 switch states 的時候就順便把裝置切成上限，讓 Device 可以少打一個 API 速度可以更快一點
- API
- 用後台取得 switch 應該不會變成上線
- 用 `oauth/exchange-token-for-device` `POST` 取得 token 再拿 switch states 時裝置應該會被切為上線

feat: 實作裝置拿開關的時候順便切成上線

---

dashboard/src/app.tsx

- 群組選單修正 hook 執行的時間點
- as title
- 登入後臺看一下是否有出現下圖有 `切換群組` 的選單但是沒有內容

fix: 修正選單讀取群組資料

---

api/Dataservices/PipelineExecuteLogDataservice.cs
api/Services/ClearExpiredPipelineExecuteLogsCronJobService.cs
api/Startup.cs

- 實作定期清除 pipeline execute log 
- API
- 手動新增一筆 24h 前的 pipeline execute logs
- 手動新增一筆 10h 前的 pipeline execute logs
- 更改 startup.cs 裏頭執行清除 pipeline execute logs 的頻率
- 確認剛剛手動新增 24h 前的 pipeline execute logs 是否有被刪除，10h 的資料有被保留

feat: implement scheduled clear expired pipeline execute logs
