- f2e/src/controllers/master.controller.js
- f2e/src/swim/routing-controller.js
fix: routing controller meta mechanism
> feat: update meta

- f2e/src/components/header/header.html
- f2e/src/components/header/header.scss
- f2e/src/controllers/feature.controller.js
- f2e/src/controllers/how.controller.js
- f2e/src/css/common.scss
- f2e/src/css/zindex.scss
- f2e/src/routing-rule.js
- f2e/src/swim/cacher.js
- f2e/webpack.config.js
fix: fix rwd header,
feat: implement webpack build error in production
> fix: fix rwd header,

- f2e/src/components/footer/footer.html
- f2e/src/css/common.scss
> feat: copy right 加上 opacity 0.65 的 style

- README.md
> feat: 更新規則說明

- f2e/src/components/check-in/check-in.component.js
- f2e/src/css/common.scss
- 登記成功後將 email 寫至 cookie
- 手機版的 toaster 顯示於上方
- 前台 F2E
> feat: 登記成功後將 email 寫至 cookie，手機版的 toaster 顯示於上方

- f2e/src/components/check-in/check-in.component.js
- f2e/src/index.html
- as title
- 前台 F2E
- https://dev.itemhub.io/ 
- 登記後看一下 messenger 有沒有出現
> feat: implement facebook messenger

- f2e/src/build/index.html
- f2e/src/template/main.html
> feat: add fb messenger for build index.html

- f2e/src/build/index.html
- as title
- 前台 F2E
https://itemhub.io
> feat: update itemhub meta for building template

- api/Controllers/UserController.cs
- api/Homo.AuthApi/Constants/Error.cs
- api/Homo.AuthApi/Models/EF/DBContext.cs
- api/Localization/Error/en-US.json
- api/Localization/Error/zh-TW.json
- as title
- 前台 API
用相同 email 註冊會出現此 email 已經註冊的錯誤訊息
> feat: user validation

- f2e/.vscode/settings.json
- 新增 .vscode/setting.json 檔案，藉此讓協作夥伴的 format 一致。
- 前台 F2E ( itermhub official wrebsite )。
- Merge 這隻 PR 後，將 repo 重新拉下來，測試 f2e 專案中的 format 有沒有問題，如果有問題，可以將新的規則補在 .vscode/setting.json 中，反之，如果發現有規則是多餘的，也可以再拔掉。
> Feat/ add vscode setting for f2e repo

- website/src/build/index.html
- website/src/index.html
> feat: 把 fb sdk 讀取的時間往後推遲 3s, 提升 Page Speed 評價

- website/src/build/index.html
- website/src/index.html
> feat: try to refactor load fb sdk

- website/src/build/index.html
- website/src/index.html
- website/src/swim/cacher.js
- 把 fb sdk delay 10s 改成 3s, 剛剛沒有改善 page speed 是因為 ngxin 指到舊的 dist 位置, 現在都改為 `website/dist`, 但 nginx 指到 `f2e/dist`
- Website F2E
> feat: update cacher & load fb sdk delay 3s

- website/package.json
- website/webpack.config.js
> refactor: try to reduce css size

- website/package.json
- website/webpack.config.js
> refactor: try to convert building css to inline style into index.html

- website/src/routing-rule.js
- website/src/swim/loader.js
> refactor: swim 加上 parallel load dependency

- website/src/template/master.html
> fix: try to fix toaster style

- website/src/swim/cacher.js
- update swim cacher
- Website F2E
> feat: update swim cacher

- pull_request_template.md
> doc: update pull request template

- website/src/components/check-in/check-in.component.js
- website/src/components/check-in/check-in.html
- website/src/components/pricing-plan/pricing-plan.component.js
- website/src/controllers/main.controller.js
- website/src/controllers/pricing.controller.js
- website/src/routing-rule.js
- website/src/swim/render.js
- website/src/swim/router.js
- website/src/template/main.html
- website/src/template/pricing.html
> feat: 優化 check-in 行為, 填完資料直接反應在登記人數

- website/src/swim/base.component.js
- 修正 render recursive component 沒有 await 到,  導致 binding event 被 par…ent binding 走了
- Website F2E
> fix: 修正 render recursive component 沒有 await 到

- website/src/build/index.html
- website/src/controllers/main.controller.js
- as title
- Website F2E
https://itemhub.io/ 看一下 description 是否有包含`工廠流程自動化`, `土壤監控`, `自動澆灌`
> feat: 優化 SEO for google search

- website/src/components/check-in/check-in.html
- as title
- Website F2E
https://itemhub.io/
> feat: 移除終身免費升及進階方案的 placeholder

- website/src/css/overwrite.scss
- website/src/css/sign-in.scss
- website/src/template/sign-in.html
- 右邊區塊的底色應為 #1E202B
- 登入按鈕文字大小應為 20px
- 右邊區塊若高於左邊區塊，會有一塊空白
- 登入按鈕及社群登入的按鈕 font-weight 要是600
- Website F2E
https://dev.itemhub.io/sign-in/
> fix: 修正 sign-in style 跟設計稿不同的地方

- api/Controllers/MyDeviceController.cs
- api/Dataservices/DeviceDataservice.cs
- api/IotApi.csproj
- 實作裝置上下線機制 Ref #184 
- API
用 post man 打 POST /devices/:id/online api
看 Device.Online 有沒有變成 1 三秒後有沒有變成 0
token 需要跟 peter 拿
> feat: implement device online mechanism

- api/Controllers/MyDeviceController.cs
- api/Dataservices/DeviceDataservice.cs
- api/Services/TimeoutOfflineDeviceService.cs
> refactor: online mechanism

- website/src/components/pricing-plan/pricing-plan.html
- website/src/components/pricing-plan/pricing-plan.scss
- website/src/css/overwrite.scss
- 更新價格方案
- Ref #152
- Website F2E
https://dev.itemhub.io/
> feat: update pricing plan

- website/src/components/pricing-plan/pricing-plan.html
- website/src/components/pricing-plan/pricing-plan.scss
- website/src/css/overwrite.scss
- 修改錯字和加上 dollar sign 
- Website F2E
https://dev.itemhub.io/
> feat: update pricing plan wording

- website/src/components/pricing-plan/pricing-plan.scss
- website/src/controllers/pricing.controller.js
- website/src/template/main.html
- as title
- Website F2E
https://dev.itemhub.io/
> feat: remove free upgrade information

- website/src/components/pricing-plan/pricing-plan.scss
- remove check-in border
- Website F2E
> refactor: remove pricing plan checkin border

- api/Localization/Error/en-US.json
- api/Localization/Error/zh-TW.json
- website/src/components/header/header.component.js
- website/src/constants.js
- website/src/controllers/auth.controller.js
- website/src/controllers/sign-in.controller.js
- website/src/dataservices/universal.dataservice.js
- website/src/routing-rule.js
- website/src/template/sign-in.html
- as title
- API
- Website F2E
https://dev.itemhub.io/sign-in/
> feat: 實作社群登入

- api/README.md
> doc: update api read me

- dashboard/src/main.tsx
- dashboard/src/pages/dashboard/dashboard.tsx
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/pages/triggers/triggers.tsx
- dashboard/vite.config.ts
- as title
http://localhost:3000/dashboard/
> fix: 在連結前面加上 dashboard  prefix

- dashboard/.env.dev
- dashboard/.env.prod
- dashboard/package.json
- dashboard/src/constants.ts
- dashboard/src/dataservices/auth.dataservice.ts
- dashboard/src/dataservices/device.dataservice.ts
- dashboard/src/vite-env.d.ts
> feat: 加上 env variable

- deploy.sh
> feat: update deploy shell script

- api/Constants/AppSettings.cs
- api/Constants/Error.cs
- api/Constants/PricingPlan.cs
- api/Controllers/CheckoutController.cs
- api/Controllers/UniversalController.cs
- api/Helpers/Subscription.Helper.cs
- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/Homo.AuthApi/Dataservices/SubscriptionDataservice.cs
- api/Homo.AuthApi/Dataservices/TransactionDataservice.cs
- api/Localization/Error/en-US.json
- api/Localization/Error/zh-TW.json
- api/Models/DTOs/Checkout.cs
- api/Models/DTOs/Subscription.cs
- api/Models/DTOs/TapPayResponse.cs
- api/Models/DTOs/Transaction.cs
- api/Models/EF/IotDbContext.cs
- api/Models/EF/Subscription.cs
- api/Models/EF/Transaction.cs
- website/server.js
- website/src/components/pricing-plan/pricing-plan.html
- website/src/constants.js
- website/src/controllers/checkout.controller.js
- website/src/dataservices/checkout.dataservice.js
- website/src/dataservices/universal.dataservice.js
- website/src/routing-rule.js
- website/src/template/checkout.html
- 前台大致上實作訂閱付費
- 實作 checkout API (現在會依照定閱起始日計算月費)
- 目前還沒實作下期自動扣款的 CronJob
- API
- Website F2E
https://dev.itemhub.io/checkout/pricingPlan=0
https://dev.itemhub.io/checkout/pricingPlan=1
https://dev.itemhub.io/checkout/pricingPlan=2
> feat: 實作訂閱付費

- website/webpack.config.js
- as title
- Website F2E
NODE_ENV=dev npm run swim-build
> fix: 在 webpack.config.js 移除不需要的檔案

- website/src/swim/cacher.js
- Update Swim cacher
- Website F2E
> fix: update cacher

- dashboard/.env.dev
- dashboard/.env.prod
- dashboard/src/pages/dashboard/dashboard.tsx
- dashboard/src/vite-env.d.ts
- as title
沒登入的狀態下看一下 測試環境不會重導
http://dev.itemhub.io:3000/dashboard/
正式環境會重導到 website url
https://itemhub.io/dashboard/
> feat: 如果在驗證身份發生錯誤且是 production 環境 redirect 到 website url

- api/Services/AutoPaymentService.cs
- api/Startup.cs
- 詳情參考 https://github.com/HangfireIO/Cronos/issues/42
- API
> fix: 修正 cronjob 無法順利啟動

- dashboard/src/app.tsx
- 替 dev 環境加上簡單登入 UI，便於兩階段驗證完成前的開發登入
- 把 token 拔掉後，有 UI 可以登入（僅限於 dev site）
> feat: implement temp dashboard simple login

- api/Dataservices/DevicePinDataservice.cs
- 實作 pin state 欄位
- 本來是送兩個 query 到 db 改為送一個 query 當量大的時候 performance 會好一點
- API
登入後用 post man 打以下 api url
https://dev.itemhub.io:5001/api/v1/me/devices/60/pins
檢查資料是否長這樣, 多出 state 的欄位
```json
[
{
"pin": "D2",
"deviceId": 60,
"mode": 0,
"state": 75.000000000000000000000000000
},
{
"pin": "D2",
"deviceId": 60,
"mode": 0,
"state": 75.000000000000000000000000000
}
]
```
> api feature: 實作 pin state 欄位

- api/Controllers/MyDevicePinController.cs
- api/Dataservices/DevicePinDataservice.cs
- as title
- API
Method: `DELETE` 
Parameter: `{ "usedPins": "D0,D1,D2" }`
URL: `https://dev.itemhub.io:5001/api/v1/devices/:id/pins`
> feat: 實作 remove unused pins 給 device 用

- dashboard/src/components/pins/pins.tsx
- dashboard/src/types/devices.type.ts
- 新增 pin state type
- 將 pin state 從 api response data 拿出，並且 render 在 device page
- 在 device page 頁面，可以看到 pin state data 顯示出來
https://github.com/miterfrants/itemhub/issues/238
> Implement pin state

- api/Homo.AuthApi/Constants/Error.cs
- api/Homo.AuthApi/Controllers/AuthResetPasswordController.cs
- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyPhoneController.cs
- api/Localization/Error/en-US.json
- api/Localization/Error/zh-TW.json
- 實作 social media sign up process
- API
看 code 就好 後面會有 f2e 在跑流程
> feat: api sign up with social media api

- website/src/components/feature/feature.html
- website/src/css/common.scss
- website/src/template/master.html
- 把 body 的文字改成 opacity 85%
- 修改一些 text-white 的文字拿掉
- Website F2E
https://dev.itemhub.io/ 
看一下文字顏色, 是不是跟設計稿一樣
> feat: website update text color to opacity white

- api/Homo.Api/Filters/ValidateAttribute.cs
- api/Homo.AuthApi/Constants/Error.cs
- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- api/Localization/Error/en-US.json
- api/Localization/Error/zh-TW.json
- website/src/constants.js
- website/src/controllers/auth.controller.js
- website/src/controllers/master.controller.js
- website/src/controllers/oauth.controller.js
- website/src/controllers/sign-up.controller.js
- website/src/controllers/verify-email.controller.js
- website/src/dataservices/auth.dataservice.js
- website/src/template/sign-up.html
- website/src/template/verify-email.html
- 實作 social media sign up
- Website F2E
把 social media 註冊流程跑完, 並確認有處理 social media 有以下情況
- social media 不允許讀取 email
- social media 使用重複的 email
> feat api: sign up with social media

- api/Controllers/MyDevicePinSensorController.cs
- api/Controllers/MyTriggerController.cs
- api/Dataservices/TriggerDataservice.cs
- api/Models/DTOs/Trigger.cs
- api/Models/EF/Trigger.cs
- Ref #250
- as title
- API
透過 swagger UI 去測試 Trigger CRUD, 檢查資料格式是否符合 #250 的描述
> feat api: triggers crud

- dashboard/src/dataservices/devices.dataservice.ts
- dashboard/src/helpers/api.helper.ts
- dashboard/src/helpers/cookie.helper.ts
- dashboard/src/types/dataservices.type.ts
- dashboard/src/types/helpers.type.ts
- 把整個 dashboard 專案用 prettier 跑一次
看能不能正常在 local 把專案跑起來
> feat: run prettier for whole dashboard project

- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyPhoneController.cs
- as title
- API
測試看看是否有收到信和簡訊
> feat: 把避免測試時過度打第三方 API 被 block 的註解拿掉

- README.md
> feat: 更新相關文件連結

- api/Controllers/MyOauthClientController.cs
- dashboard/src/hooks/apis/oauth-clients.hook.ts
- dashboard/src/index.tsx
- dashboard/src/pages/oauth-client/oauth-client.tsx
- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- dashboard/src/redux/reducers/oauth-clients.reducer.ts
- dashboard/src/types/oauth-clients.type.ts
- as title
http://localhost:3000/dashboard/oauth-clients
http://localhost:3000/dashboard/oauth-clients/create
> feat: implement crate oauth-client

- api/Controllers/MyTriggerController.cs
- as title
- API
登入後打
`https://localhost:5001/api/v1/me/triggers/1` `GET` 看一下是否有回傳類似這樣格式的資料
```json
{
"id": 1,
"createdAt": "2021-12-02T00:42:58.858881",
"editedAt": null,
"ownerId": 23,
"deletedAt": null,
"sourceDeviceId": 56,
"sourcePin": "D1",
"sourceThreshold": 62.000000000000000000000000000,
"sourceDevice": null,
"destinationDeviceId": 56,
"destinationPin": "D0",
"destinationDevice": null,
"destinationDeviceSourceState": 0.0000000000000000000000000000,
"destinationDeviceTargetState": 1.0000000000000000000000000000,
"operator": 0
}
```
> feat: 實作漏掉的 get single trigger api

- dashboard/src/components/pagination/pagination.stories.tsx
- dashboard/src/components/pagination/pagination.test.tsx
> hotfix: fix build dashboard error when vite run pagination component test

- build-for-production.sh
- 加上 production build shell script
- Dev Ops
> feat: add shell script to build for produciton

- dashboard/src/components/pagination/pagination.stories.tsx
- dashboard/src/components/pagination/pagination.test.tsx
- dashboard/src/redux/reducers/triggers.reducer.ts
- as title
npm run build 看一下會不會發生錯誤
> fix: 修正少改了 rowNums

- .gitignore
> feat: 避免 static 整個資料夾被加到版本控管

- deploy.sh
> dev-ops: 實作 githb flow

- website/src/template/main.html
> feat: test github flow

- website/src/controllers/checkout.controller.js
- as title
- Website F2E
https://dev.itemhub.io/checkout/?pricingPlan=1 看一下會不會跳出錯誤 Toaster 如果不會就是修好了
> fix: 修正沒有登入狀態 redirect 到登入頁面的路徑不對

- api/Homo.AuthApi/Constants/AppSettings.cs
- api/Homo.AuthApi/Controllers/AuthTwoFactorController.cs
- api/Homo.AuthApi/Dataservices/VerifyCodeDataservice.cs
- api/Homo.AuthApi/Models/DTOs/VerifyCode.cs
- api/Homo.AuthApi/Models/EF/DBContext.cs
- api/Homo.AuthApi/Models/EF/VerifyCode.cs
- api/Localization/Error/zh-TW.json
- website/src/components/header/header.component.js
- website/src/components/header/header.html
- website/src/constants.js
- website/src/controllers/sign-in.controller.js
- website/src/controllers/two-factor-auth.controller.js
- website/src/css/common.scss
- website/src/dataservices/auth.dataservice.js
- website/src/routing-rules/auth.routing-rule.js
- website/src/template/two-factor-auth.html
- Ref: #258
-  實作兩階段驗證包含 API 和 Website
- API
- Website F2E
https://dev.itemhub.io/
> feat: two factor auth

- api/.gitignore
- api/Startup.cs
- website/src/swim/cacher.js
- 實作在測試機可以跑 migration db code
- 更新 website swim cache
- API
- Website F2E
No
> dev ops migration

- dashboard/src/redux/reducers/oauth-clients.reducer.ts
同 https://github.com/miterfrants/itemhub/pull/306，只是回到 dev 環境。
- 進入這個網址 [http://localhost:3000/dashboard/oauth-clients/27](http://localhost:3000/dashboard/oauth-clients/27%EF%BC%8C%E9%87%8D%E6%96%B0%E6%95%B4%E7%90%86%E9%A0%81%E9%9D%A2%EF%BC%8C%E4%B8%8D%E6%9C%83%E5%86%8D%E9%87%8D%E8%A4%87%E6%89%93) ，重新整理頁面，不會再重複打API
@miterfrants @vickychou99
> hotfix: fix-oauth-client-render-loop-bug (to dev)

- dashboard/src/hooks/apis/devices.hook.ts
- dashboard/src/pages/device/device.tsx
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/redux/reducers/devices.reducer.ts
- Ref: #308 
- 實作刪除裝置
http://localhost:3000/dashboard/devices/63
> feat: remove device

- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/Homo.AuthApi/Controllers/AuthTwoFactorController.cs
- website/src/controllers/sign-out.controller.js
- website/src/controllers/sign-up-finish.controller.js
- website/src/controllers/sign-up.controller.js
- Ref #316 
- 註冊流程會直接拿到 Dashboard Token
- Website F2E
- 跑註冊流程檢查是否會拿到 Dashboard Token 
> feat: sign up could be get dashboard token

- api/Constants/Error.cs
- api/Controllers/MySubscriptionController.cs
- api/Homo.AuthApi/Dataservices/SubscriptionDataservice.cs
- api/Localization/Error/zh-TW.json
- website/src/constants.js
- website/src/controllers/me.controller.js
- website/src/dataservices/subscription.dataservice.js
- website/src/routing-rule.js
- website/src/template/me.html
- Ref #158 
- `/me/` 會顯示使用者現在訂閱的方案
- 實作取消訂閱的按鈕
- API
- Website F2E
- 先跑訂閱流程或是用 Peter 的帳號登入
- 嘗試取消訂閱重新整理頁面看是否真的有取消, 並在群組裡頭詢問看有沒有收到 itemhub.tw@gmail.com 轉發的取消訂閱信件
> feat: cancel subscription

- api/Dataservices/DeviceActivityLogDataservice.cs
- api/Services/DeviceActivityLogCronJobService.cs
- api/Startup.cs
- Ref #327 
- API
- 327 有寫測試方式
> feat: clear device activity log

- dashboard/.gitignore
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/vite.config.ts
- deploy.sh
- as title
- Dev Ops 
- 在 `./dashboard/` 資料夾底下加上 .env.staging 
```
VITE_API_URL=https://itemhub.homo.tw/api/v1/
VITE_ENV=staging
VITE_WEBSITE_URL=https://itemhub.homo.tw
```
- Terminal `npm run build-staging` 看是否會發生錯誤
> feat: dev ops separate dashboard staging building npm command

- api/Homo.AuthApi/Helpers/AuthHelper.cs
- website/src/controllers/verify-email.controller.js
- 優化重覆註冊的提醒文字
- Ref  #329 
- API
- Website F2E
> feat: 優化提醒文字

- api/Migrations/20220319193723_change-stop-next-subscription-default-value.Designer.cs
- api/Migrations/20220319193723_change-stop-next-subscription-default-value.cs
- api/Models/EF/IotDbContext.cs
- StopNextSubscribed default 改為 0 ( false )
- API
- 確認預設值改為 0
> feat: 修改 Subscription StopNextSubscribed default value

- api/Homo.AuthApi/Constants/AppSettings.cs
- api/Homo.AuthApi/Constants/Error.cs
- api/Homo.AuthApi/Controllers/AuthSignInController.cs
- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/Homo.AuthApi/Controllers/AuthUpdateEarlyBirdController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- api/Homo.AuthApi/Dataservices/UserDataservice.cs
- api/Homo.AuthApi/Models/DTOs/Auth.cs
- api/Localization/Common/en-US.json
- api/Localization/Common/zh-TW.json
- api/Localization/Error/en-US.json
- api/Localization/Error/zh-TW.json
- website/src/constants.js
- website/src/controllers/sign-up.controller.js
- website/src/dataservices/auth.dataservice.js
- website/src/template/sign-up.html
- Ref #256 
- API
- Website F2E
- 透過通知信綁定
- 透過 email 綁定
> feat: 實作早鳥用戶綁定

- api/Homo.AuthApi/Constants/AppSettings.cs
- api/Homo.AuthApi/Controllers/AuthRemoveFbSubController.cs
- api/Homo.AuthApi/Controllers/AuthResetPasswordController.cs
- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/appsettings.template.json
- Ref: #346 
- API
- 參考 Issues
> feat: 將 websiteEndpoint 改成 websiteUrl

- api/Controllers/OauthController.cs
- as title
- API
- `POST` `/api/v1/oauth/exchange-token-for-device` 
- 換到 dashboard token
- `GET` `/api/v1/me/devices/by-device-id/{deviceId}` 看會不會拿到資料
> fix: 裝置登入應該要有 User Id 來確認使用者是誰, 避免建立無人的 Device Id

- api/Constants/Error.cs
- api/Controllers/MyDevicePinSensorController.cs
- api/Filters/FilterRequestAttribute.cs
- api/Filters/FilterRequestFactory.cs
- api/Helpers/Subscription.Helper.cs
- api/Localization/Error/zh-TW.json
> feat: 實作超過訂閱方案時丟出相對應的錯誤

- api/Filters/FilterRequestAttribute.cs
> fix: 修正 check 上一次 request log 時 log 是 null

- api/Filters/FilterRequestAttribute.cs
> fix: 修正 filter request npe

- api/Dataservices/DevicePinSensorDataservice.cs
- api/Helpers/Subscription.Helper.cs
- api/Services/ClearExpiredDevicePinSensorDataCronJobService.cs
> fix: 修正 cronjob clear sensor pin data npe

- api/Dataservices/DevicePinSensorDataservice.cs
- api/Helpers/Subscription.Helper.cs
- api/Services/ClearExpiredDevicePinSensorDataCronJobService.cs
> hotfix: fix clear sensor pin data cronjob npe

- api/Dataservices/DevicePinSensorDataservice.cs
> fix: 修正清除 sensor data 發生 NPE

- api/Dataservices/DeviceActivityLogDataservice.cs
- api/Services/DeviceActivityLogCronJobService.cs
> fix: try to fix dead lock when clear activity logs

- website/src/css/common.scss
- Ref https://github.com/miterfrants/itemhub/issues/357
- as title 
- Website F2E
- 在 header.component.js render function 裡頭
```
setTimeout(() => {
Toaster.popup(Toaster.TYPE.INFO, 'testing', 50000);
}, 1000);
```
- 看一下手機 style toaster 是否會置中
> fix: 修正 website toaster style erroor

- dashboard/src/css/common.scss
- dashboard/src/css/overwrite.scss
- dashboard/src/css/zindex.scss
- dashboard/src/pages/dashboard/dashboard.module.scss
- dashbaord 加上 common style
- 確認 common style 可以正常運行
@miterfrants
> feat: dashboard 加上 common style

- dashboard/src/components/footer/footer.tsx
- dashboard/src/pages/dashboard/dashboard.module.scss
- dashboard/src/pages/dashboard/dashboard.tsx
> feat: 讓 dashboard 目前看得到文字

- dashboard/src/css/common.scss
> feat: 修改預設字體設定

- deploy.sh
> fix: 修正 run docker 少了把加密的 key 塞到 docker

- api/Services/DeviceActivityLogCronJobService.cs
> hotfix:try to fix delete activity log

- api/Services/DeviceActivityLogCronJobService.cs
> fix: try to fix delete activity log cornjob

- website/src/css/checkout.scss
- website/src/swim/cacher.js
> feat: 修正 tabpay field style bug 和 更新 swim build cache

- api/Controllers/MyOauthClientController.cs
- api/Dataservices/OauthClientDataservice.cs
- api/Migrations/20220412073507_AddDeviceIdForOauthClient.Designer.cs
- api/Migrations/20220412073507_AddDeviceIdForOauthClient.cs
- api/Models/EF/IotDbContext.cs
- api/Models/EF/OauthClient.cs
- dashboard/src/helpers/api.helper.ts
- dashboard/src/hooks/apis/oauth-clients.hook.ts
- 加上 device id for oauth client 
- oauth client 列表不會顯示 device client 的資料
- Ref: #395
- API
> feat: add device id for oauth client

- website/src/components/footer/footer.html
- website/src/controllers/agreements.controller.js
- website/src/routing-rule.js
- website/src/template/agreements.html
> feat: 新增服務條款

- api/Services/SendOverPlanNotificationCronJobService.cs
> feat: 修改超過訂閱方案提醒信件的週期

- dashboard/src/pages/devices/devices.tsx
- as title
http://localhost:3000/dashboard/devices
> fix: 修正 dashboard devices 圖片路徑

- api/Controllers/MyOauthClientController.cs
- api/Models/DTOs/OauthClient.cs
- dashboard/src/components/page-title/page-title.tsx
- dashboard/src/constants/api.ts
- dashboard/src/hooks/apis/fetch.hook.ts
- dashboard/src/hooks/apis/oauth-clients.hook.ts
- dashboard/src/pages/device/device.tsx
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/types/oauth-clients.type.ts
- 實作 device id 專屬的 oAuthClient, 目前還沒實作在建立 device 當下同時建立 oAuthClient  
- API
> feat: 實作 device oauth-client

- dashboard/src/components/pagination/pagination.tsx
- dashboard/src/pages/oauth-clients/oauth-clients.scss
- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- as title
http://localhost:3000/dashboard/oauth-clients/?page=2
> feat: 實作 pagination style

- dashboard/src/components/page-title/page-title.tsx
> feat: 修正 page title component 使用 import image source

- api/Controllers/MyDeviceController.cs
- api/Dataservices/DeviceDataservice.cs
- dashboard/src/hooks/apis/devices.hook.ts
- dashboard/src/pages/devices/devices.tsx
- as title
- API
http://localhost:3000/dashboard/devices
> feat: 實作 filter devices name

- api/Dataservices/DeviceActivityLogDataservice.cs
> fix: 修正清除 Activity Logs

- dashboard/src/components/page-title/page-title.tsx
- dashboard/src/components/pin/pin.tsx
- dashboard/src/pages/devices/devices.scss
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/pages/oauth-clients/oauth-clients.tsx
> feat: 修正 style

- dashboard/src/pages/devices/devices.tsx
> feat: 修正圖片路徑

- dashboard/src/components/pin/pin.tsx
- Ref #419 
- 點到以下網址 http://localhost:3000/dashboard/devices/60 
- 打開 console network 看一下是進到頁面就會打 `PATCH` `https://dev.itemhub.io:5001/api/v1/my/devices/60/switches/D0` API 
- 如果沒有才是正常的 
@LiangYingC
> fix: 修正點進 Device 頁面就打 Patch API

- dashboard/src/components/header/header.scss
- dashboard/src/redux/reducers/menu.reducer.ts
- 修正手機版預設不會關閉 menu
- 確認在手機版的時候，預設有關閉 menu
> feat: 修正手機版預設不會關閉 menu

- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- as title
http://localhost:3000/dashboard/oauth-clients 
> feat: 修改 oauthclient page size

- api/Dataservices/DeviceActivityLogDataservice.cs
- api/Dataservices/DeviceDataservice.cs
- api/Services/StartupOfflineService.cs
- api/Startup.cs
> feat: 主機重啟後先檢查是否有裝置需要切換為下線

- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- as title
http://localhost:3000/dashboard/oauth-clients
> feat: 實作 oauthclient 列表選擇全部或是取消全部功能

- dashboard/src/components/pin/pin.scss
- 修正 device list toggle button 在 safari 上的樣式問題
> fix: fix dashboard toggle button style bug in safari

- dashboard/src/hooks/apis/devices.hook.ts
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/redux/reducers/devices.reducer.ts
- 把 Devices Store 改成 devices: DeviceItem[] ->  { rowNum: number, devices: DeviceItem[]}
- 修改 device redux action 的名稱
http://localhost:3000/dashboard/devices/
> feat: 實作 devices pagination

- api/Constants/AppSettings.cs
- api/Controllers/MyTransactionController.cs
- api/Controllers/TappayController.cs
- api/Localization/Common/en-US.json
- api/Localization/Common/zh-TW.json
> feat: 實作當有付費會員時，發信給管理員

- dashboard/src/hooks/apis/devices.hook.ts
- dashboard/src/pages/device/device.tsx
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/redux/reducers/devices.reducer.ts
- 實作刪除 device
- 把 deleteDevice action 改成 deviceDevices action  單數變複數
http://localhost:3000/dashboard/devices
> feat: 實作 delete device in devices list

- .gitignore
- api/static/email/contact-us.html
- api/static/email/early-bird-register.html
- api/static/email/new-premium-user.html
- api/static/email/over-subscription copy.html
- api/static/email/over-subscription.html
- api/static/email/reset-password.html
- api/static/email/two-factor-auth.html
- api/static/email/verify-email.html
- as title
- API
- 確認 email template
> feat: upload email template

- api/Services/SendOverPlanNotificationCronJobService.cs
> fix: 修正超過訂閱通知信拿錯 template

- dashboard/src/redux/reducers/oauth-clients.reducer.ts
> fix: dashboard remove countOfAllClient in oAuthClientState type

- dashboard/.gitignore
- deploy.sh
> fix: 修正 staging server deploy script

- api/static/email/contact-us.html
- api/static/email/early-bird-register.html
- api/static/email/new-premium-user.html
- api/static/email/over-subscription.html
- api/static/email/reset-password.html
- api/static/email/two-factor-auth.html
- api/static/email/verify-email.html
- as title
- API
- 確認 logo 與 logo wording 中間有間距
> feat: 修正通知 mail 的 logo 圖的間距

- api/Homo.AuthApi/Controllers/AuthResetPasswordController.cs
- api/Homo.AuthApi/Controllers/AuthSignInController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- Ref: #456 
- API
- 確認 isEarlyBird 判斷皆改為 DB 欄位判斷
> feat: 將 isEarlyBird 判斷改用 DB 欄位判斷

- dashboard/src/components/toaster/toaster.tsx
- as title
- http://localhost:3000/dashboard/oauth-clients
- 刪除後跳出 Toaster, 嘗試按下右方叉叉看會不會運作
> fix: 修正 toaster 關閉沒有運作

- api/Dataservices/DeviceActivityLogDataservice.cs
- api/Services/TimeoutOfflineDeviceService.cs
> fix: 修正 device 沒有正常下線的問題

- dashboard/src/components/input/search-input/search-input.tsx
- dashboard/src/components/toaster/toaster.tsx
- dashboard/src/hooks/apis/triggers.hook.ts
- dashboard/src/pages/triggers/triggers.tsx
- dashboard/src/types/triggers.type.ts
Ref: https://github.com/miterfrants/itemhub/issues/481
- 可以 by trigger name 搜尋（先前缺把 trigger name 傳進 useGetTriggers api 中）
- 實作 delete trigger one 功能，並確保不影響 delete triggers
- 實作 delete one / multiple 後，均會跳出 toaster
- 在 triggers 頁面，確認刪除 triggers / trigger 均正常
@miterfrants @vickychou99
> Feat/ trigger name search and delete one trigger

- README.md
> doc: update project structure description

- dashboard/package.json
- dashboard/src/css/overwrite/tooltip.scss
- dashboard/src/index.scss
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- dashboard/src/pages/triggers/triggers.tsx
- #514 
- as title 
- 要安裝 node package 跑一次 `npm i`
- 檢查所有列表頁的按鈕是否有出現 tooltip  e.g
> feat: 實作 tooltip

- dashboard/src/components/footer/footer.tsx
- dashboard/src/components/pin/pin.tsx
- dashboard/src/css/overwrite/utilities.scss
- dashboard/src/css/tag.scss
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- dashboard/src/pages/triggers/triggers.tsx
- 設定 `bs`的 fs  class 對應的字體大小
- 將 class h6 換成 fs-5
- 將 class h5 換成 fw-bold ( h5 為 16px = body font size)
> feat: implement font size style

- dashboard/src/css/common.scss
- dashboard/src/pages/devices/devices.scss
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- dashboard/src/pages/triggers/triggers.scss
- dashboard/src/pages/triggers/triggers.tsx
- 實作 row hover style
- 重構 triggers, devices html 把重複的 row 結構改成一層
- 點擊 row 的時候會直接勾選每一列最前方的 checkbox
- hover style 背景會變淺藍色
- http://localhost:3000/dashboard/triggers 點擊一列任何一個位置都會勾選 checkbox
> feat: row hover style

- api/Homo.AuthApi/Controllers/AuthSignInController.cs
- api/Localization/Error/zh-TW.json
- as title
- API
- 確認已綁定電話的早鳥用戶可正常登入
- 確認未綁定電話的早鳥用戶會正常跳提示訊息
> feat: 修正早鳥用戶的判斷及提示訊息

- api/Services/FirmwareGenerateService.cs
- dashboard/src/index.scss
- 修正解 conflict 錯誤, DevicePinDataservice 已經沒有 GetList function 全部都改為 GetAll
- 修正之前改資料夾名稱但是沒有更新 scss import 路徑
- API
- API 可以正常運作
- Dashboard F2E 可以 run 的起來
> fix: 修正之前改資料夾名稱但是沒有更新 scss import 路徑

- api/Controllers/GoogleSmartHomeController.cs
- api/Models/DTOs/GoogleSmartHome.cs
> fix: 修正 google smart home api

- api/Controllers/OauthController.cs
- firmware/arduino-nano-33-iot/arduino-nano-33-iot.ino
- firmware/esp-01s/ItemhubUtilities/ItemhubUtilities.h
- firmware/esp-01s/esp-01s.ino
- firmware/particle-io-photon/particle-io-photon.ino
- API oAuth Exchange Token 時同時把 DeviceId 送出去
- 移除 Firmware 把不必要的 Code 拿掉
- Ref #507 
- API
看 code 應該就可以了
> feat: 改在授權的時候就取得 remote device id

- website/src/template/sign-in.html
- website/src/template/verify-email.html
- #540
- website remove fb sign up 
- website remove fb sign in 
- Website F2E
- https://dev.itemhub.io/auth/verify-email/
- https://dev.itemhub.io/auth/sign-in/
> Feat/remove fb sign in/sign up

- api/Controllers/GoogleSmartHomeController.cs
- api/Dataservices/DevicePinDataservice.cs
- as title
- API
- 可以看 code 就好, 避免 device name 空字串
> fix: 避免 google smart home 回傳名字空白造成 google smart home connect error

- dashboard/src/css/common.scss
> fix: style bug 現在都改由 .list:hover 來帶入 style, 移除本來的 .row:hover 帶來的介面效果

- api/Homo.AuthApi/Dataservices/MicrocontrollerDataservice.cs
- api/Services/FirmwareGenerateService.cs
- 之前取得 firmware 的方式是來自於 device mcu constant, 現在改成 mcu id from db
- API
確認你的 device 是有選擇特定類型的晶片, 可以看資料 Device.Microcontroller, 確認有值以後可以點擊打包程式碼, 如圖
> fix: 修正 bundle firmware bug

- dashboard/src/components/header/header.scss
> fix: 修正 rwd menu 蓋住了靠近左側的連結

- api/Controllers/MyDeviceController.cs
- as title
- API
- 先查一下目前使用者的訂閱方案, 可以新增多少個 Device
- 新增更多 device 看會不會跳出錯誤訊息
> fix: 修正沒有訂閱的使用者在這邊會發生 NPE, 修正超越目前平台制定的方案的判斷式

- api/Services/FirmwareGenerateService.cs
- api/Services/TimeoutOfflineDeviceService.cs
- 印出正式 API static path 看是否是錯誤的位置
- API
> test: try to print api static path

- dashboard/src/hooks/apis/oauth-clients.hook.ts
- dashboard/src/redux/reducers/devices.reducer.ts
- dashboard/src/redux/reducers/pins.reducer.ts
- as title
- 用 redux dev tool 看每一個更新是否都有觸發 redux store 更新
> fix: 修正更新 redux 單一資料時沒有真的更新

- dashboard/src/helpers/api.helper.ts
- as title 
- Dashboard
- 確認 api 回傳錯誤時，toaster 有顯示錯誤訊息
> feat: api 產生 error 的時候，用 toaster 顯示錯誤訊息

- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- as title
- 確認新增 device 時，需必填 device name 及 選擇 PIN 
> feat: 新增 device 的時候，檢查必填資訊

- api/Homo.AuthApi/Controllers/AuthTwoFactorController.cs
- as title
- API
重新登入 dashboard 看一下 cookie 裡頭 dashboardToken 的過期時間
> feat: 修改 dashboard 過期時間為 14 天

- dashboard/src/pages/trigger/trigger.tsx
- https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=908%3A19625 
http://localhost:3000/dashboard/triggers/edit/73
> refactor: 修改 trigger style follow figma designer 修改

- api/Homo.Api/Middlewares/ErrorHandlingMiddleware.cs
- api/IotApi.csproj
- api/Program.cs
- #610 
- 串接 sentry io (目前先不串接, 經濟考量)
- 把 stackTrace 資訊拿掉
- API
- 嘗試輸入用隨機的帳號密碼登入, 挑出找不到對應的使用
- 檢查 Network 是否 response 沒有顯示 stackTrace 欄位
> feat: 把 stack trace 拿掉

- website/src/components/feature/feature.html
- website/src/components/feature/feature.scss
- as title
- ref: #609 
- Website F2E
- 確認 website 文案及 style
> feat: 修改 feature 的文案

- website/src/components/header/header.html
- as title
- Website F2E
https://dev.itemhub.io
> fix: 修正 website header rwd bug

- website/src/components/check-in/check-in.html
- website/src/components/check-in/check-in.scss
- website/src/components/feature/feature.html
- website/src/components/how-to-use/how-to-use.html
- website/src/css/main.scss
- website/src/template/main.html
- as title
- Website F2E
- 檢查修改內容是否有錯綴字
> refactor: website wording

- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- as title
- 原先新增完後會跳轉至裝罝編輯頁新增 oAuth Client ，但後來不用新增 oAuth Client 了，所以直接導至裝置明細頁，可直接打包下載程式碼
- 確認新增完裝置後，是跳轉至裝置明細頁
> feat: 新增完裝置後改跳轉至裝置明細頁

- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- dashboard/src/pages/device/device.tsx
- dashboard/src/pages/devices/devices.tsx
- as title
- 確認 `打包`程式碼 都有換成 `下載`程式碼
> feat: 文字調整，把打包程式碼，換成下載程式碼，這樣比較好懂

- website/src/components/how-to-use/how-to-use.html
- Ref: #174 
- 優化 how to use 
- Website F2E
- 確認文案內容
> feat: 優化 how to use 文案

- dashboard/src/pages/device/device.tsx
- dashboard/src/pages/devices/devices.tsx
- device 列表頁點選下載程式碼按鈕時，跳 toaster 訊息提醒
- 下載程式碼的 toaster 文案優化
- 確認 device 列表頁點下載程式碼後，有出現 toaster
- 確認下載程式碼的 toaster 文案
> feat: 優化 device

- website/src/components/header/header.html
> feat: 修改 header nav item 中文

- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- Ref: #629 
- 確認可以修改 pin name 
> feat: 實作修改 pin name 功能

- api/Controllers/CheckoutController.cs
- api/Homo.AuthApi/Dataservices/SubscriptionDataservice.cs
- as title
- 付款失敗需刪除訂閱資料
- Website F2E
- 確認付款失敗時，會刪除訂閱資料
> feat: tappay response 回傳不是 OK 的時候, 刪除訂閱資料

- website/src/build/index.html
- as title
- Website F2E
看 code 就可以了, 如果要在 local 測試 
- 把 src/build/index.html 的 script 貼到 src/index.html 裡頭
- 接著開啟 console 看讀取 freshchat sdk 的時候是不是在紅線後面才發生
> refactor: 延遲載入 freshchat 避免影響 UI 操作

- dashboard/src/components/inputs/autocompleted-search/autocompleted-search.tsx
- dashboard/src/pages/trigger/trigger.tsx
- fix trigger source, target device data list bug
- refactor: 新增完 trigger 資料後回到列表頁
http://localhost:3000/dashboard/triggers/create 
> fix: 修正 trigger 來源裝置沒有正常運作

- dashboard/package.json
- dashboard/src/app.tsx
- dashboard/src/helpers/cookie.helper.ts
- dashboard/src/types/helpers.type.ts
- website/src/controllers/oauth.controller.js
- website/src/controllers/sign-in.controller.js
- website/src/controllers/sign-up.controller.js
- website/src/controllers/two-factor-auth.controller.js
- website/src/util/cookie.js
- as title
- Website F2E
- 登入後檢查 console application cookies 裡頭的 Expires 是否有過期時間 (本來是顯示工作階段)
> feat: 設定 token 的時候把 exp 塞到 cookie 避免關掉瀏覽器的時候 token 就被清掉

- api/Constants/Subscription.cs
- api/Controllers/CheckoutController.cs
- api/Controllers/MySubscriptionController.cs
- api/Controllers/OauthController.cs
- api/Controllers/TappayController.cs
- api/Homo.AuthApi/Dataservices/SubscriptionDataservice.cs
- api/Homo.AuthApi/Dataservices/TransactionDataservice.cs
- api/Localization/Common/en-US.json
- api/Localization/Common/zh-TW.json
- api/Migrations/20220526160747_update.Designer.cs
- api/Migrations/20220526160747_update.cs
- api/Models/DTOs/Subscription.cs
- api/Models/EF/IotDbContext.cs
- api/Models/EF/Subscription.cs
- api/Services/SendOverPlanNotificationCronJobService.cs
- as title
- API
- 跑訂閱流程看會不會發生錯誤
- 輸入錯誤的卡號看資料庫是否有正常把 tappay 回來的 response 存下來
> fix: 修正 tappay 回傳錯誤的時候會有 NPE

- website/src/controllers/two-factor-auth.controller.js
> fix: 修正兩階段驗證後更換後台 token, response property name 寫錯

- api/Controllers/CheckoutController.cs
- checkout 印出 postbody 的內容
- tappay 正式機付款失敗, 要從checkout 印出 postbody 的內容提供給 tappay
- API
- 確認有印出 postbody 的內容
> feat: checkout 印出 postbody 的內容

- api/Migrations/20220520171241_GenerateEarlyAdapterFirstSubscription.cs
> feat: date 格式加上單引號

- api/Controllers/CheckoutController.cs
- api/Migrations/20220520171241_GenerateEarlyAdapterFirstSubscription.cs
> feat: 更新正式機

- api/Controllers/CheckoutController.cs
- 修正訂閱金額低於 1 元時以 1 元計算
- 修正訂閱金額計算時少加 1 天
- API
- 跑訂閱流程看一下金額會不會變成零元 (本來會, 現在應該修正好了)
> fix: 修正訂閱金額

- website/src/template/transaction.html
- title
- Website F2E
- 跑結帳流程看一下最後交易畫面是否有正常顯示
@vickychou99
> fix: 隱藏一些不需要再等待交易時顯示的資訊

- api/Controllers/TappayController.cs
> refactor: 嘗試把 tappay 丟給我們的資訊印出來

- api/Controllers/CheckoutController.cs
- as title, 加上 log 要給 tappay 資料
- API
- 確認有印出 log
> feat: checkout 加上 log

- website/src/components/header/header.html
- as title
- Website F2E
應該看 code 就可以了
> feat: 修改 header nav item padding top and bottom in mobile device

- api/Controllers/TappayController.cs
- Ref: #668
- API
- 於本機測試打 tappay api，看看有沒有印資料出來
> feat: 修正 tappay 接收的參數從 dynamic 換成 frombody

- api/Homo.AuthApi/Controllers/AuthResetPasswordController.cs
- as title
- API
- 確認一下自己的帳號是 早鳥帳號 User.IsEarlyBird = 1 
- 確認資料的帳號是已經跑完所有驗證 User.PseudonymousPhone != null
- 跑忘記密碼流程看是否能正常運作
> fix: 修正忘記密碼不管你是不是完成驗證, 只要是早鳥就會跳出缺少電話的錯誤訊息

- api/Controllers/MyDeviceController.cs
> fix: 修正 subscription npe

- website/src/controllers/how.controller.js
- website/src/template/how.html
- as title
- Website F2E
https://dev.itemhub.io/how/
> feat: 實作 website how to use 架構

- dashboard/src/css/card.scss
- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- dashboard/src/pages/device/device.tsx
- Ref: #365 
- 確認手機版的 device 頁同設計稿
- https://www.figma.com/file/eqxlwbzWPRrdMDCede74yX/itemhub?node-id=1715%3A59976
> feat: 實作 device rwd

- website/src/template/how.html
- how to use 新增: 如何開始使用 Itemhub、如何用 Itemhub 串接 Google Smart Home
- Website F2E
- 確認 how to use 的文案內容
> Feat: how to use 新增內容

- website/src/controllers/sign-up.controller.js
> fix: 修正驗證手機時, 輸入匡被 disabled

- api/Controllers/CheckoutController.cs
- api/Controllers/TappayController.cs
- api/Homo.AuthApi/Dataservices/SubscriptionDataservice.cs
- api/Services/AutoPaymentCronJobService.cs
- 當期若已經有訂閱資料，將現有的訂閱資料刪除後，在新增訂閱資料，才不會有重覆訂閱的問題
- 自動訂閱的條件更新
- 修正通知管理員的信件參數沒取代到
- 移除之前測試印出的 console
- API
- 依照修改內容測試
> feat: 修正自動訂閱

- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- #682 
- as title
http://localhost:3000/dashboard/devices/create
> fix: 修正 arduino nano 33 IoT 名稱, 這個未來應該要改成從 back-end 來的 key

- website/src/controllers/checkout.controller.js
- as title
- Website F2E
- 確認持卡人的姓名顯示正確
> feat: 修正訂閱時顯示的持卡人姓名

- website/src/template/how.html
- as title
- Website F2E
- 確認 how to use 電腦版/手機版 頁面正常
> feat: how to use rwd 版面修正

- dashboard/src/pages/device/device.tsx
- website/src/components/feature/feature.html
- website/src/components/footer/footer.html
- website/src/components/header/header.html
- website/src/components/header/header.scss
- website/src/components/how-to-use/how-to-use.html
- website/src/components/pricing-plan/pricing-plan.html
- website/src/template/auth.html
- website/src/template/checkout.html
- website/src/template/how.html
- website/src/template/main.html
- website/src/template/transaction.html
- 修正 dashboard 當裝置名稱太長的時候，欄位名稱的寬度會變小
- 修正 website 的 style
- 確認裝置名稱超過2行時，欄位名稱的寬度不會變小
- 確認 website 的 style 都正常
> feat: fix-style

- dashboard/src/pages/trigger/trigger.tsx
- dashboard/src/pages/triggers/triggers.tsx
- as title
- API
- 確認編輯 trigger 時，是直接導到編輯頁
> feat: 編輯 trigger 時，直接導到編輯頁

- dashboard/src/pages/triggers/triggers.tsx
- as title
http://localhost:3000/dashboard/triggers
> fix: 修正點擊 tigger 列表的刪除會跳到編輯頁面

- dashboard/src/components/inputs/tags-input/tags-input.tsx
- dashboard/src/css/overwrite/variables.scss
- as title
- 確認 tag input style
> feat: 修改 tag input style

- dashboard/src/css/button.scss
- as title
- 確認 button disabled 的時候，沒有原按鈕的框線顏色
> feat: fix button disabled 的 框線

- api/Services/DeviceActivityLogCronJobService.cs
> feat: 修正 cronjob 回傳資料的問題

- api/Homo.Api/Middlewares/ErrorHandlingMiddleware.cs
- 如果是 cronjob 的話, reqBody 跟 queryString 會是 null，就直接 retun 
- API
- 確認程式正常
> feat: 修正錯誤處理

- api/Homo.Api/Middlewares/ErrorHandlingMiddleware.cs
- as title
- API
- 確認有錯誤訊息的時候，有正常送 sentry
> feat: 優化錯誤處理，避免塞爆 sentry

- api/Homo.AuthApi/Constants/Error.cs
- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- api/Localization/Error/en-US.json
- api/Localization/Error/zh-TW.json
- as title
- Website F2E
- 確認早鳥用戶綁定帳號後，重新至註冊頁面發送驗證碼時，有跳提醒通知
> feat: EMAIL註冊發送驗證碼時，若已綁定帳號的早鳥用戶跳提醒已註冊提醒

- api/Services/AutoPaymentCronJobService.cs
- 修正自動訂閱每天都發生
- 修正自動訂閱沒有把訂閱狀態切成已付款
- API
跑每分鐘自動訂閱的 cronjob 
> fix: 修正自動訂閱每天都發生

- api/Services/AutoPaymentCronJobService.cs
- api/Startup.cs
- as title
- API
- 確認是 6/10 1:30 AM 執行
> feat: 改執行 AutoPaymentCronJob 時間, 正式機測試 AutoPaymentCronJob

- api/Startup.cs
- as title 
- API
- 確認改成 1:50 AM 執行
> feat: AutoPaymentCronJob 改 1:50 AM 執行

- api/Constants/AppSettings.cs
- api/Services/AutoPaymentCronJobService.cs
- api/Startup.cs
- as title
- API
- 確認 auto payment 使用的是非 3D 驗證的 MerchantId 
> feat: auto payment 改用非 3D 驗證的 MerchantId

- api/Startup.cs
- as title
- API
- 確認 autopayment cronjob 時間是 3:15 AM
> feat: 修改 autopayment cronjob 時間

- api/Startup.cs
> Feat: change autopayment cronjob time

- api/Services/AutoPaymentCronJobService.cs
- api/Startup.cs
- as title
- API
- 確認 autopayment cronjob 執行時間為每月1號 00:00
> Feat: 恢復 autopayment cronjob 執行時間, 移除 log

- api/Controllers/CheckoutController.cs
- website/src/template/forget-password.html
- website/src/template/reset-password.html
- website/src/template/sign-in.html
- website/src/template/sign-up.html
- website/src/template/verify-email.html
- as title
- Website F2E
- 確認使用 `貼上` 的時候，也會觸發相對應的 event ，如驗證 email 格式
> hotfix: 輸入框直接貼上值的時候，沒有觸發 onkeyup ，所以所有輸入框都加上 onchange event

- api/Controllers/CheckoutController.cs
- website/src/template/forget-password.html
- website/src/template/reset-password.html
- website/src/template/sign-in.html
- website/src/template/sign-up.html
- website/src/template/verify-email.html
- as title
- Website F2E
- 確認使用 `貼上` 的時候，也會觸發相對應的 event ，如驗證 email 格式
> hotfix: 輸入框直接貼上值的時候，沒有觸發 onkeyup ，所以所有輸入框都加上 onchange event 

- website/src/components/check-in/check-in.component.js
- website/src/controllers/forget-password.js
- website/src/controllers/reset-password.js
- website/src/controllers/sign-in.controller.js
- website/src/controllers/sign-up.controller.js
- website/src/controllers/verify-email.controller.js
- keycode 的判斷增加 event.type 為 keyup 的條件，避免當 event 是 onchage 的時候會出錯
- Website F2E
- 確認使用電腦按 enter 的時候，有正常觸發按鈕 event 
> feat: event 有可能是 onchage , 所以增加 keyup 判斷

- website/src/components/check-in/check-in.component.js
- website/src/controllers/forget-password.js
- website/src/controllers/reset-password.js
- website/src/controllers/sign-in.controller.js
- website/src/controllers/sign-up.controller.js
- website/src/controllers/verify-email.controller.js
- keycode 的判斷增加 event.type 為 keyup 的條件，避免當 event 是 onchage 的時候會出錯
- Website F2E
- 確認使用電腦按 enter 的時候，有正常觸發按鈕 event 
> Hofix: event 有可能是 onchage , 所以增加 keyup 判斷 #771

- api/Controllers/MyDevicePinController.cs
- api/Dataservices/DevicePinDataservice.cs
- dashboard/src/components/pin/pin.tsx
- dashboard/src/components/pins/pins.tsx
- dashboard/src/hooks/apis/device.pin.hook.ts
- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- dashboard/src/pages/device/device.tsx
- dashboard/src/redux/reducers/pins.reducer.ts
- dashboard/src/types/devices.type.ts
- refactor: 優化 redux 避免一直打相同的 API
- refactor: 優化 device pin 相關的 code
- 從裝置列表點擊到單一頁面看一下是否有多打拿 Device API
- 從單一裝置預覽頁面到編輯頁面檢查是否有多打 Pins API 
- 跑整個裝置流程看是否有問題
> refactor: 優化 device pin 相關的 code

- api/Constants/DashboardMonitor.cs
- api/Controllers/MyDashboardMonitorController.cs
- api/Dataservices/DashboardMonitorDataservice.cs
- api/Migrations/20220616082543_AddDashbaordMonitor.Designer.cs
- api/Migrations/20220616082543_AddDashbaordMonitor.cs
- api/Models/DTOs/DashboardMonitor.cs
- api/Models/EF/DashboardMonitor.cs
- api/Models/EF/IotDbContext.cs
- 實作 Dashboard monitor api 
- API
詳情可參考 Swagger UI
- GET `/api/v1/my/dashboard-monitors`
- POST `/api/v1/my/dashboard-monitors`
- PATCH `/api/v1/my/dashboard-monitors/{id}`
- DELETE `/api/v1/my/dashboard-monitors`
> feat: implement dashboard monitor api

- api/Services/FirmwareGenerateService.cs
> fix: remove print for bundle error

- website/src/routing-rule.js
- 修改 routing rule 讓 sitemap 正常
- Website F2E
- 確認 routing rule 正確
- build website 看 sitemap 是否正常
> feat: fix-sitemap

- api/Controllers/MyDevicePinSwitchController.cs
> fix: 修改 取得所有開關 PIN 的 Swagger 說明

- dashboard/src/pages/dashboard/dashboard.tsx
- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- dashboard/src/pages/device/device.tsx
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/pages/oauth-client/oauth-client.tsx
- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- dashboard/src/pages/trigger/trigger.tsx
- dashboard/src/pages/triggers/triggers.tsx
- Ref: #784 
- 確認每個頁面的 page title 是正確的
> feat: 新增 dashboard page title

- api/Dataservices/SensorLogDataservice.cs
- dashboard/src/components/dashboard-monitor/line-chart-monitor/line-chart-monitor.tsx
- as title
http://localhost:3000/
> fix: 修正 dashboard monitor line chart日期顯示

- api/Controllers/MyDevicePinSensorController.cs
- api/Helpers/Subscription.Helper.cs
- as title
- #812 
- API
- 在資料庫 Trigger.Phone 改自己的電話
- 打 POST sensor 的 API 看會不會收到簡訊
> feat: 實作 sms notification & 修改 notification rate limit

- dashboard/package-lock.json
- as title
只要看 code 就好, merge 完可以看有 line chart 的 dashboard, 看會不會 crash 
> fix: update package lock

- api/Controllers/UniversalController.cs
- website/src/components/pricing-plan/pricing-plan.html
- website/src/template/checkout.html
- Ref: #811 
- API
- Website F2E
> feat: website 價格方案增加 email 通知數量

- dashboard/src/pages/trigger/trigger.tsx
- dashboard/src/types/triggers.type.ts
- Ref: #848 
- 確認可正常新增 / 修改 trigger 
> feat: 修正新增 trigger 時，目標狀態的預設值

- api/Migrations/20220704174120_UpdatePinMaxLength.Designer.cs
- api/Migrations/20220704174120_UpdatePinMaxLength.cs
- api/Migrations/20220704175256_UpdatePinMaxLength5.Designer.cs
- api/Migrations/20220704175256_UpdatePinMaxLength5.cs
- api/Models/DTOs/DevicePin.cs
- api/Models/DTOs/Trigger.cs
- api/Models/EF/SensorLog.cs
- api/Models/EF/Trigger.cs
- as title
- API
- 選晶片 ESP01-S 新增 Trigger 的時候會套出 Validation Error
> feat: 修改 PIN 腳允許的最大長度改為 5

- dashboard/src/components/inputs/autocompleted-search/autocompleted-search.tsx
- dashboard/src/components/inputs/device-and-pin-input/device-and-pin-input.tsx
- dashboard/src/components/inputs/search-input/search-input.tsx
- dashboard/src/components/pagination/pagination.tsx
- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- dashboard/src/pages/device/device.tsx
- dashboard/src/pages/devices/devices.tsx
- dashboard/src/pages/trigger/trigger.tsx
- dashboard/src/pages/triggers/triggers.tsx
- dashboard/src/types/common.type.ts
- #809 
- 修正有些 edge case 會造成搜尋沒有正常運作 e.g 輸入搜尋文字按下 enter 然後刪除後很快按下 enter 不回回到原本完整資料的列表
- 透過 url 紀錄搜尋條件, 並且在任一狀態重新整理頁面都會回復到原本的頁面狀態
- 拿掉 AutoComplete DataList 一些不必要的 code
- Trigger List Page
- Device List Page
> feat: 修正搜尋的 bug 

- website/src/swim/cacher.js
- as title
- Website F2E
https://itemhub.homo.tw/
> feat: 因為有新增 router, 所以要更新 swim cache

- website/src/controllers/how.controller.js
- website/src/swim/cacher.js
> fix: 修正 build 完以後 scrolling handler 沒有正常被 trigger

- dashboard/src/pages/triggers/triggers.tsx
- #810
- as title
http://localhost:3000/dashboard/triggers 測試刪除
> fix: 修正 Delete Trigger 無法正常刪除的問題

- api/Controllers/UniversalController.cs
- website/src/components/pricing-plan/pricing-plan.html
- website/src/template/checkout.html
- Ref: #869 
- API
- Website F2E
- 確認 pricingPlan 及 checkout 頁都有新增簡訊說明
> feat: website 加上 sms 通知的說明

- api/Controllers/GoogleSmartHomeController.cs
> feat: 如果裝置名稱有 light 或是 燈, 對應到的 Device Type 就改為 LIGHT

- website/src/swim/cacher.js
> fix: 修正沒有對應的檔案

- website/src/components/how-to-start/how-to-start.html
- as title
- Website F2E
- 確認文字正確
> feat: 移除重覆的文字

- dashboard/src/components/device-pin/device-pin.tsx
- as title
- 確認重新命名 pin name 正常
> hotfix: 修正第二次重新命名 PIN 時會無法運作的問題

- dashboard/src/components/device-pin/device-pin.tsx
- as title
- 確認重新命名 pin name 的取消按鈕有正常運作
> feat: 修正重新命名 pin name 的取消按鈕沒有正常運作

- api/Homo.AuthApi/Controllers/SystemMailController.cs
- api/Homo.AuthApi/Dataservices/UserDataservice.cs
- api/Homo.AuthApi/Models/DTOs/SystemMail.cs
- Ref: #905
- API
- 確認 API 可正常發送
> feat: 問卷改一封一封發

- api/Models/DTOs/Firmware.cs
- api/Services/FirmwareGenerateService.cs
> feat: node mcu A0 pin 的 value 是 string ，所以把 mcu 的 value 換成 string

- api/Constants/MailTemplate.cs
- api/Controllers/ContactController.cs
- api/Controllers/MyDevicePinSensorController.cs
- api/Controllers/TappayController.cs
- api/Helpers/MailTemplateHelper.cs
- api/Homo.AuthApi/Controllers/AuthResetPasswordController.cs
- api/Homo.AuthApi/Controllers/AuthTwoFactorController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- api/Homo.AuthApi/Controllers/SystemMailController.cs
- api/Homo.AuthApi/Helpers/MailHelper.cs
- api/Services/SendOverPlanNotificationCronJobService.cs
> feat: 修改 mail helper 命名空間

- api/Program.cs
- deploy.sh
- as title
- #925 
- API 
看 code 就可以了, 等 deploy 完以後連到 homo 主機, port 改為 18330
> feat: 讓測試機可以使用 MQTT

- deploy.sh
> 修正 mqtt port

- api/Filters/IotAuthorizeFactory.cs
- api/Filters/IotDashboardAuthorizeFactory.cs
- api/Homo.AuthApi/Constants/AppSettings.cs
- api/Homo.AuthApi/Controllers/AuthRefreshTokenController.cs
- api/Homo.AuthApi/Controllers/AuthSignInController.cs
- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/Homo.AuthApi/Controllers/AuthTwoFactorController.cs
- api/Homo.AuthApi/Controllers/AuthUpdateEarlyBirdController.cs
- api/Homo.AuthApi/Filters/AuthorizeFactory.cs
- api/Program.cs
- website/server.js
- website/src/components/header/header.component.js
- website/src/constants.js
- website/src/controllers/oauth.controller.js
- website/src/controllers/sign-in.controller.js
- website/src/controllers/sign-up.controller.js
- website/src/controllers/two-factor-auth.controller.js
- website/src/dataservices/auth.dataservice.js
- website/src/routing-rule.js
- 實作 Refresh token
- API
- Website F2E
- `routing-rule.js` 修改 132 行, 把 jwtLifeHours 印出來
- `routing-rule.js` 修改 137 行, 把 jwtLifeHours < 3 * 24 改成將要過期的數字
- 重新整理看有沒有重新取得 token
- `two-factor-auth.controller.js` 修改 38 行, 把 jwtLifeHours 印出來
- `two-factor-auth.controller.js` 修改 44 行, 把 jwtLifeHours < 12 改成將要過期的數字
- 重新整理看有沒有重新取得 token
> feat: refresh token

- website/src/swim/loader.js
- as title
- #890 
- 因為網站最前會載入 gtag, 這個有 dependency 會等到 gtag load 完才進到 routing, 如果沒 load 完就會一直 load 到 timeout 並停止所有運作, 現在把規則改成 timeout 還是繼續跑 routing
- Website F2E
- install duckduck go ext
- 把測試站開起來, 看使否會變成空白
> fix: duckduck ext

- website/src/build/index.html
- as title
- #938 
- Website F2E
- initiateCall 這個只能在 build 過的環境上看得到, 所以看 code 就好
> fix: 修正首頁本來會跑 fresh chat 的 initial 的 function 但後來換掉了沒把這一段拿掉

- dashboard/src/pages/trigger/trigger.tsx
- Ref #933 
- 確認 trigger 的目標狀態有正常顯示
> feat: 修正 trigger 目標狀態的預設值

- website/src/components/how-to-implement-autopot/how-to-implement-autopot.html
- website/src/components/how-to-implement-hygrometer/how-to-implement-hygrometer.html
- website/src/components/how-to-integrate-google-nest/how-to-integrate-google-nest.html
- website/src/components/how-to-start/how-to-start.html
- Ref: #937
- Website F2E
- 確認影片可正常播卡
- 確認文案正確
> feat: 加上 youtube 影片及優化文案

- website/src/components/how-to-implement-hygrometer/how-to-implement-hygrometer.html
- website/src/components/how-to-implement-hygrometer/how-to-implement-hygrometer.scss
- Ref: #937 
- Website F2E
- http://dev.itemhub.io/how/implement-hygrometer/#step1
- 確認 youtube 影片有滿版顯示
> fix: youtube 影片改滿版顯示

- api/Constants/MailTemplate.cs
- api/Helpers/MailTemplateHelper.cs
- api/Homo.AuthApi/Constants/Error.cs
- api/Homo.AuthApi/Controllers/SystemMailController.cs
- api/Homo.AuthApi/Models/DTOs/SystemMail.cs
- static/email/invite.html
- Ref: #928 
- API
- 測試可正常發送客製信
- api link: http://dev.itemhub.io:5000/api/v1/system-mail/custom-email
- template json
```
{
"TemplateName":"INVITE",
"Email":"vickychou99@gmail.com",
"Subject":"Hi Vicky 你好2",
"Content":"邀請你使用 itemhub",
"IsUser":true
}
```
> feat: 新增客製信件

- api/Dataservices/OauthClientDataservice.cs
- api/IotApi.csproj
- api/Program.cs
- api/Startup.cs
- as title
- #910
- API
- 跟 peter 要 mqtt-tls server cert 放在 api/secrets/mqtt-server-cert.pfx
- 跟 peter 要 mqtt tls client cert 在連線的時候需要這個
- 使用 mqtt client software 啟用 TLS 並選擇剛剛要到的 mqtt tls client cert 
- 連線看是否有正常連到
- 測試關掉 TLS 是否連得到
- 測試把 client cert 拿掉是否連得到
> feat: 實作 MQTT TLS self signed certification

- api/Properties/launchSettings.json
> feat: api 改成不走 https

- api/Services/FirmwareGenerateService.cs
- as title
- API
- run `git submodule update --init --recursive --remote`
- 測試在 Local 是否可以正常下載 firmware 
> feat: firmware 變成兩種資料夾 http, mqtt

- deploy.sh
- mqtt tls port 在 startup.cs 已經改為 8883 修改 deploy script
- API
No, 直接 merge 在測試機做連線
No
> feat: update mqtt tls port

- api/Controllers/MqttController.cs
- api/Controllers/MyDeviceController.cs
- api/Controllers/MyDevicePinSensorController.cs
- api/Controllers/MyDevicePinSwitchController.cs
- api/Helpers/DeviceSensorHelper.cs
- api/Helpers/DeviceStateHelper.cs
- api/Helpers/DeviceSwitchHelper.cs
- api/Helpers/MqttBrokerHelper.cs
- api/Startup.cs
- implement intermediate certificate
- implement permission of mqtt subscription
- move re-used code to helper function
- API
- 透過 mqtt client 看是否能正常連線
- 嘗試用 mqttx 訂閱 263/D0/switch 看是否會被斷線, 如果被斷線代表正常. 這個 PR 主要是避免訂閱其他人的裝置狀態
> feat: implement permission of mqtt subscription

- api/Helpers/DeviceSensorHelper.cs
- api/Homo.Api/Middlewares/ErrorHandlingMiddleware.cs
- api/Startup.cs
- 嘗試修正高乘載 cpu 
- API
看 code 就可以
> skip over rate limit error handler

- api/Helpers/DeviceSensorHelper.cs
> fix: 嘗試修正 cpu 高乘載的問題

- website/src/components/header/header.component.js
- website/src/components/header/header.html
- as title
- Website F2E
header 加上 API 連結讓匿名的使用者可以看到 API 文件
> feat: 把 API 選單加到 Header 上方

- .gitignore
- guideline/README.md
- guideline/dev-ops/db/manually-dump-tips.md
- 增加 tips 
- guideline
- 確認內容正確
> feat: 增加 guide line tips 

- guideline/README.md
- 更新 guideline 路徑結構
- guideline
- 確認路徑正確
> feat: 更新 guideline 路徑結構

- api/Services/SendOverPlanNotificationCronJobService.cs
> feat: 修正超過訂閱方案時，提醒信件內容沒有被取代

- api/Controllers/UniversalController.cs
- api/Migrations/20221017235207_AddSupportedProtocols.Designer.cs
- api/Migrations/20221017235207_AddSupportedProtocols.cs
- api/Models/EF/Microcontroller.cs
- dashboard/src/pages/device-pin-data/device-pin-data.tsx
- dashboard/src/types/universal.type.ts
- By Commit 看
- Ref: #1000
- API: Microcontroller 加上 SupportedProtocols
- API: 更新資料庫
- Dashboard: 加上 Supported Protocols 如果只有一種 Protocol 就會顯示 `僅支援 XXXX` 如果有多個才會出現下拉選單
- API
http://localhost:3000/dashboard/devices/edit/{deviceId}
測試一下新增修改刪除看一下行為有沒有不在預期內
> mcu supported protocols

- api/Controllers/MyDevicePinSwitchController.cs
- api/Dataservices/DevicePinDataservice.cs
- api/Models/DTOs/DevicePin.cs
- as title
- API
`v1/my/devices/{id}/switches` 只輸出 id, value, pin 三個欄位
> feat: device api 輸出必要欄位就好, 避免記憶體不夠造成 crash

- dashboard/src/components/inputs/autocompleted-search/autocompleted-search.tsx
- dashboard/src/components/inputs/device-and-pin-input/device-and-pin-input.tsx
- dashboard/src/components/inputs/search-input/search-input.tsx
- dashboard/src/pages/device-view/device-view.tsx
- dashboard/src/pages/trigger/trigger.tsx
- dashboard/src/pages/triggers/triggers.tsx
> feat: remove default value

- api/Controllers/LogController.cs
- api/Dataservices/LogDataservice.cs
- api/Migrations/20221217120611_AddLog.Designer.cs
- api/Migrations/20221217120611_AddLog.cs
- api/Models/DTOs/Log.cs
- api/Models/EF/IotDbContext.cs
- api/Models/EF/Log.cs
- as title
- #1029
- API
- url `/api/v1/log`
- payload
```json
{"deviceId": 12, "message": "testing"}
```
> feat: implement log for device

- api/Migrations/20221221213039_AddDevicePinDefaultValue.Designer.cs
- api/Migrations/20221221213039_AddDevicePinDefaultValue.cs
- api/Models/EF/IotDbContext.cs
- as title
- API
新增 device pin 的時候 如果是空值，再切換的時候會不觸發 api
> feat: add device pin default value

- api/Homo.AuthApi/Controllers/AuthDropSelfController.cs
-  #1046 
- API
- 登入後打以下 API
- URL `api/v1/auth/drop-self`
- method `POST`
> feat: implement delete user api

- api/Controllers/MyDeviceActivityLogController.cs
- api/Dataservices/DeviceActivityLogDataservice.cs
- dashboard/src/constants/api.ts
- dashboard/src/hooks/apis/device-last-activity-logs.hook.ts
- dashboard/src/pages/device-view/device-view.tsx
- dashboard/src/redux/reducers/device-activity-logs.reducer.ts
- dashboard/src/redux/store.ts
- dashboard/src/types/devices.type.ts
- 新增 device activity log  api 
- API
- 登入後打 `/v1/my/devices/:id/activity-logs?page=1&limit=1` 
> feat: implement device activity log api

- api/Dataservices/DevicePinDataservice.cs
- as title
- API
新增 PIN 以後會有 default value
> feat: default value for device pin

- dashboard/src/components/dashboard-monitor/current-value-monitor/current-value-monitor.tsx
- dashboard/src/components/dashboard-monitor/line-chart-monitor/line-chart-monitor.tsx
- website/src/controllers/two-factor-auth.controller.js
-  #1024 
- 打開 chrome console 檢查把 toggle button 切成 live 的時候 network 會不會每五秒去打一次 API
- 到資料表 SensorLog 加上新資料 CreatedAt 改成現在的時間看一下表會不會更新
> feat: implement pooling for line chart

- dashboard/src/hooks/apis/device-last-activity-logs.hook.ts
- 修正 build error: redux type error
- 在 Local run `npm run build-staging` 看能不能順利 build 完
> fix: redux type error

- dashboard/src/components/dashboard-monitor/current-value-monitor/current-value-monitor.scss
- dashboard/src/components/dashboard-monitor/current-value-monitor/current-value-monitor.tsx
- dashboard/src/components/dashboard-monitor/line-chart-monitor/line-chart-monitor.tsx
- dashboard/src/components/dashboard-monitor/switch-monitor/switch-monitor.scss
- dashboard/src/components/dashboard-monitor/switch-monitor/switch-monitor.tsx
- dashboard/src/pages/dashboard/dashboard.tsx
- 稍微優化 RWD
在 dashboard 加上各種 monitor 然後縮放 window 尺寸，檢查有沒有不太合理或是完全無法觀看的狀態
> feat: update dashboard rwd style

- api/Constants/AppSettings.cs
- api/Homo.AuthApi/Constants/AppSettings.cs
- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyPhoneController.cs
- 固定 email 驗證碼 for testing
- 固定特定電話的驗證碼 for testing
- API
- `{{endpoint}}/api/v1/auth/send-verify-email` `post`
- `{{endpoint}}/api/v1/auth/send-verify-phone` `post`
- secrets.json 要加上資料請跟 Peter 要
> feat: fixed verify code for testing

- api/Homo.AuthApi/Controllers/AuthTwoFactorController.cs
- 兩階段驗證如果是測試信箱，傳回固定的 verify code
- API
- 註冊一個 secrets.json 設定的 TestingEmail 帳號
- 登入後取得 token 
- 打 `/api/v1/auth/send-two-factor-auth-mail` POST  API 帶入 token 應該不會收到 Email，然後檢查 VerifyCode Table 應該會塞入 `000000`
> feat: two factor auth for testing

- api/Dataservices/DeviceActivityLogDataservice.cs
- #1066 
- API
http://localhost:3000/dashboard/devices
- 需要建立至少兩筆資料看是不是顯示最近的一筆
- 滑到裝置列上方出現 title 看一下最後上線時間是否正常
> feat: 修正最後上線時間

- dashboard/src/components/device-pins/device-pins.tsx
- Ref: #1067 
- 編輯 PIN 的名稱時，切換到中文選字完按下 Enter 後，不會關閉視窗及更新資料
> feat: 修正編輯 PIN 的名稱時，中文選字完按下 Enter 後會關閉視窗並更新資料

- dashboard/src/pages/device-form/device-form.tsx
- Ref: #1069
- 至編輯裝置頁，點選 MCU 的選項，確認自定義的選項在最下方
> feat: 修改 MCU 排序

- dashboard/src/components/dashboard-monitor/current-value-monitor/current-value-monitor.tsx
- dashboard/src/components/dashboard-monitor/line-chart-monitor/line-chart-monitor.tsx
- dashboard/src/components/dashboard-monitor/switch-monitor/switch-monitor.tsx
- as title 
- 確認 dashboard 的狀態顯示在有資料與沒資料時，都是正常的
> feat: 修正 dashbaord 上線狀態的 style

- api/Controllers/MyDevicePinSensorController.cs
- api/Controllers/MyDevicePinSwitchController.cs
- 如題
- API
- 打 switch toggle api 看一下會不會 online
- 打 sensor api 看一下會不會 online
> feat: 更新 switch 或是新增 sensor log 的時候會 trigger device online

- api/Controllers/MyDevicePinSwitchController.cs
- 移除切換開關時 device online 的 Trigger
- API
- 打切換 switch 的 API, 檢查本來 Offline Device 是否會被切上線 (預期應該要不更動狀態)
> feat: remove toggle switch trigger online device state

- dashboard/package-lock.json
- dashboard/package.json
- #1087 
在 Sensor Log 加上以上幾筆資料看會不會出現 Infinite Loop Error
> fix: fix reaviz line chat infinite loop

- api/Services/SendOverPlanNotificationCronJobService.cs
- as title
- #1090 
- API
參考 Issues
> fix: 修正超越訂閱方案提醒信件發生 Exception

- dashboard/src/components/offline-notification-dialog/offline-notification-dialog.tsx
> fix: 修正 input notification npe

- api/Dataservices/DeviceActivityLogDataservice.cs
- api/Services/TimeoutOfflineDeviceService.cs
- #1110 
- API
- 打 online API `v1/my/devices/:id/online` `POST`
- 等 15 秒，就的程式這時候會下線，但應該要這時候還是線上，等到六十秒後再重新整理頁面看是否已經下線
> feat: 修改下線倒數條件

- dashboard/src/pages/device-form/device-form.tsx
- dashboard/src/pages/device/device.tsx
- dashboard/src/pages/devices/devices.tsx
- website/src/components/feature/feature.html
- website/src/components/how-to-implement-autopot/how-to-implement-autopot.html
- website/src/components/how-to-implement-hygrometer/how-to-implement-hygrometer.html
- website/src/components/how-to-start/how-to-start.html
- website/src/components/how-to-use/how-to-use.html
- #1094 
- Website F2E
應該看 code 就可以了，只是改 wording
> feat: 把程式碼都改為 sample code

- dashboard/src/components/header/header.tsx
- dashboard/src/pages/pipeline/pipeline.tsx
- dashboard/src/pages/pipelines/pipelines.tsx
- as title 
- 檢查 nav bar 
- 檢查 Pipeline 列表
- 檢查 Pipeline 編輯, Pipeline 新增
> 把 Pipeline 換成自動化出發流程

- api/Services/FirmwareGenerateService.cs
> fix: 修正某些 mcu 的 firmware 沒有 certs.h 的檔案造成錯誤

- api/Helpers/MqttPublisherHelper.cs
- #1125
- API
- 有時候會出現多重新整理 Monitor 頁面
> fix: try to fix mqtt connect error already connected

- api/Helpers/MqttPublisherHelper.cs
- api/Services/FirmwareGenerateService.cs
- api/Startup.cs
- as title
- API
- Firmware
- 測試 mqtt arduino nano 33 IoT 的 Firmware 是否可以正常運作
> feat: 修正 nano 33 IoT mqtt 的 firmware & 把 mqtt connection 印出來確認出錯的 connection 狀態

- api/Services/FirmwareGenerateService.cs
- 如果 firmwave 檔案存在的話再去讀取檔案
- API
- 確認可正常下載 firmwave 
> hotfix: 如果 firmwave 檔案存在的話再去讀取檔案

- dashboard/src/components/pipeline-flow/pipeline-flow.tsx
> refactor: remove console log

- dashboard/src/components/custom-pipeline-item/custom-pipeline-item.tsx
- dashboard/src/components/custom-pipeline-item/notification-pipeline-item.tsx
- dashboard/src/components/monitor-config-dialog/monitor-config-dialog.tsx
- 更新 pipeline item 下拉選單的 style 
> refactor: update pipleine item select style

- api/Controllers/MyPipelineController.cs
- api/Factories/PipelineFactory/SchedulePipeline.cs
- api/Helpers/PipelineHelper.cs
- api/Services/RestorePrevisousStateService.cs
- api/Services/TimeoutOfflineDeviceService.cs
- #1156
- as title
- API
- 看一下在介面上啟用時是否需要等 5 秒
> feat: 加上參數避免使用者在啟用的時候要等五秒

- dashboard/src/components/pipeline-flow/pipeline-flow.tsx
- as title
在不同的 pipeline 切換有時候會出現空白的畫面
> fix: 修正 pipeline item 有時候會是空白的

- api/Controllers/ContactController.cs
- api/Models/DTOs/ContactUs.cs
- static/email/contact-us.html
- website/src/components/header/header.html
- website/src/constants.js
- website/src/controllers/smart-agriculture.controller.js
- website/src/dataservices/contact.dataservice.js
- website/src/routing-rule.js
- website/src/swim/cacher.js
- website/src/template/smart-agriculture.html
- website/src/util/validate.js
- Ref: #1130 
- API
- Website F2E
> Feat: 實作智慧農業介紹頁

- api/Factories/PipelineFactory/SwitchPipeline.cs
> fix: 修正某些狀況會在連線 MQTT 的時候發生錯誤造成沒有更新 switch 狀態

- dashboard/src/components/pipeline-flow/pipeline-flow.tsx
- as title
- 
- http://localhost:3000/dashboard/pipelines/{id}
- 拖拉 Pipeline Item 看一下是否會跳回原來的位置又跳到當前的位置
> fix: 修正 pipeline items 再拖拉的時候會一直 re-render

- dashboard/src/components/pipeline-flow/pipeline-flow.tsx
- #1175 
pipeline list -> pipeline item -> pipeline list -> other pipeline item
看連線是否會正常出現
> fix: 修正 pipeline 連線有時候會是空白的

- dashboard/src/pages/device-form/device-form.tsx
- #1197 
https://itemhub.io/dashboard/devices/create 選擇任何一個 mcu ，在第一次沒有選擇 protocol 他 default 是 HTTP，但新增的時候他會認定你沒有選擇 protocol
> fix: fix device protocol default value

- api/Dataservices/PipelineExecuteLogDataservice.cs
- api/Factories/PipelineFactory/NotificationPipeline.cs
- Avoid sending more than two notifications within thirty mins
- #1202 
- API
> refactor: Avoid sending more than two notifications within thirty mins

- api/Controllers/MyDevicePinSensorController.cs
- api/Dataservices/SensorLogDataservice.cs
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/chart-plugins/custom-canvas-background-color.ts
- dashboard/src/chart-plugins/inner-x-axes-ticks.ts
- dashboard/src/chart-plugins/inner-y-axes-ticks.ts
- dashboard/src/components/dashboard-monitor/line-chart-monitor/line-chart-monitor.scss
- dashboard/src/components/dashboard-monitor/line-chart-monitor/line-chart-monitor.tsx
- dashboard/src/components/monitor-config-dialog/monitor-config-dialog.tsx
- dashboard/src/constants/line-chart-options.ts
- dashboard/src/hooks/apis/sensor-logs.hook.ts
- dashboard/src/index.scss
- dashboard/src/pages/dashboard/dashboard.scss
- dashboard/src/pages/dashboard/dashboard.tsx
- as title
- #1205 
- API
- 先去測試資料庫複製已經存在的資料
```
INSERT INTO SensorLog (CreatedAt, OwnerId, Pin, Value, DeviceId)
SELECT CreatedAt, {{YourUserId}}, {{YourDevicePin}}, Value, {{YourDeviceId}},
FROM SensorLog
WHERE OwnerId= 370;
```
- `nvm use 18 && npm i` (安裝 chartjs)
- 開啟網址 `https://localhost:3000/dashboard/devices`  把你的 device 加到 Dashboard 裏頭，選擇 Line Chart
- 檢查 `https://localhost:3000/dashboard` 切換不同時間區間看資料是否正常顯示
> feat: implement time range of line chart monitor

- website/src/components/how-to-implement-smart-ac/how-to-implement-smart-ac.html
- 補上智慧冷氣的接腳
- Website F2E
https://itemhub.io/how/implement-smart-ac/#step3-3
> feat: 更新智慧冷氣的接腳

- website/src/routing-rule.js
- website/src/routing-rules/auth.routing-rule.js
- 加上 google ads property id
- Website F2E
No
> feat: update google ads property id

- api/Factories/PipelineFactory/NotificationPipeline.cs
- dashboard/src/components/custom-pipeline-item/notification-pipeline-item.tsx
- as title
- API
https://github.com/miterfrants/itemhub/pull/1207
> fix: 修正 Pipeline Notification 參數錯誤 造成沒有真的間隔三十分鐘才送通知

- dashboard/src/pages/dashboard/dashboard.tsx
> fix: Fix toggle button so that they will all be linked.

- dashboard/src/components/dashboard-monitor/line-chart-monitor/line-chart-monitor.tsx
- dashboard/src/components/dashboard-monitor/switch-monitor/switch-monitor.tsx
- dashboard/src/css/overwrite/utilities.scss
- dashboard/src/css/overwrite/variables.scss
- dashboard/src/pages/dashboard/dashboard.scss
- dashboard/src/pages/dashboard/dashboard.tsx
> refactor: refine rwd of dashboard in small device

- dashboard/src/pages/devices/devices.tsx
- dashboard/src/pages/oauth-clients/oauth-clients.tsx
- dashboard/src/pages/pipelines/pipelines.tsx
> feat: fix pagination bug

- api/Controllers/MqttController.cs
- api/Controllers/MyDeviceController.cs
- api/Controllers/MyDevicePinSensorController.cs
- api/Helpers/DeviceStateHelper.cs
- api/Services/TimeoutOfflineDeviceService.cs
- static/email/offline-notification.html
> feat: 修正下線通知的 email logo & admin email 的顯示

- api/Dockerfile
> feat: 增加預設語言為中文

- dashboard/src/pages/dashboard/dashboard.scss
- dashboard/src/pages/dashboard/dashboard.tsx
> fix: 修正 rwd card 沒有限制在 dashboard 那一頁會造成所有的 card 在  mobile device 都消失

- website/src/components/how-to-implement-smart-ac/how-to-implement-smart-ac.html
- 在把冷氣變聰明的文案補一些說明，讓使用者比較知道要改哪邊
- Website F2E
http://dev.itemhub.io/how/implement-smart-ac/#step1
> refactor: Add some subsidy explanations.

- dashboard/src/components/monitor-config-dialog/monitor-config-dialog.scss
- dashboard/src/components/monitor-config-dialog/monitor-config-dialog.tsx
- dashboard/src/constants/api.ts
- dashboard/src/hooks/apis/dashboard-monitor.hook.ts
- dashboard/src/pages/dashboard/dashboard.tsx
- dashboard/src/redux/reducers/dashboard-monitor.reducer.ts
- dashboard/src/redux/reducers/monitor-config-dialog.reducer.ts
- as title
- #1239
http://localhost:3000/dashboard/
- 測試新增後的 monitor 是否可以修改版位和 pins
- 測試原本功能是否正常尤其是本來新增的功能
> feat: 實作 monitor item layout

- api/Controllers/MyDeviceController.cs
> fix: 修正 device id 就算不存在也能上傳圖片

- api/Migrations/20230625140919_AddDevicePinTypeDefaultValue.Designer.cs
- api/Migrations/20230625140919_AddDevicePinTypeDefaultValue.cs
- api/Models/EF/IotDbContext.cs
- as title
- API
新增一個 device pin type default value
> feat: 加上 default pin type

- api/Constants/PipelineItemType.cs
- api/Controllers/MyDevicePinSensorController.cs
- api/Controllers/UniversalController.cs
- api/Dataservices/SensorLogDataservice.cs
- api/Factories/PipelineFactory/SensorPipeline.cs
- dashboard/src/assets/images/analytics.svg
- dashboard/src/components/pin/pin.tsx
- dashboard/src/components/pins/pins.tsx
- dashboard/src/constants/api.ts
- dashboard/src/hooks/apis/sensor-logs.hook.ts
- dashboard/src/index.scss
- dashboard/src/index.tsx
- dashboard/src/pages/device-pin-statistics/device-pin-statistics.scss
- dashboard/src/pages/device-pin-statistics/device-pin-statistics.tsx
- dashboard/src/pages/devices/devices.tsx
-  #1294 
- API
- http://localhost:3000/dashboard/devices
- 點擊圈選起來的地方
- 檢查各種類型的資料是否正確
> feat: 實作 sensor 統計資料

- api/Constants/MailTemplate.cs
- api/Controllers/MyGroupInvitationController.cs
- api/Helpers/MailTemplateHelper.cs
- api/Homo.AuthApi/Constants/InvitationStatus.cs
- api/Homo.AuthApi/Dataservices/InvitationDataservice.cs
- api/Homo.AuthApi/Models/DTOs/Invitation.cs
- api/Homo.AuthApi/Models/EF/DBContext.cs
- api/Localization/Common/en-US.json
- api/Localization/Common/zh-TW.json
- api/Migrations/DB/20230630152850_AddInvitation.Designer.cs
- api/Migrations/DB/20230630152850_AddInvitation.cs
- api/Migrations/DB/20230701075517_AddInvitationIndex.Designer.cs
- api/Migrations/DB/20230701075517_AddInvitationIndex.cs
- api/Models/EF/Invitation.cs
- dashboard/src/components/invitation/invitation.tsx
- dashboard/src/constants/api.ts
- dashboard/src/hooks/apis/invitations.hook.ts
- dashboard/src/pages/group/group.tsx
- dashboard/src/redux/reducers/groups.reducer.ts
- dashboard/src/redux/reducers/invitations.reducer.ts
- dashboard/src/redux/store.ts
- dashboard/src/types/invitation.type.ts
- static/email/invite-to-join-group.html
- 如標題
- #1275
- API
- http://localhost:3000/dashboard/groups 新增群組
- http://localhost:3000/dashboard/groups/:id 
- 檢查 Email 以及未來連結會有帶入 group token
> feat: 實作邀請進入群組的功能

- dashboard/src/components/device-pins/device-pins.tsx
- dashboard/src/helpers/validation.helper.ts
- dashboard/src/pages/device-form/device-form.tsx
- as title 
- #1311 
- http://localhost:3000/dashboard/devices/edit/{deviceId}
- 修改 pin 名稱
> fix: 修正自定義 pin 的名稱的時候輸入中文按下 enter 就會關掉輸入匡

- api/Dataservices/DevicePinDataservice.cs
- api/Migrations/20230712183357_AddDashboardMonitor.Designer.cs
- api/Migrations/20230712183357_AddDashboardMonitor.cs
- api/Models/EF/DashboardMonitor.cs
- api/Models/EF/DevicePin.cs
- 更新 schema 把 Pin.Value 變成不允許空值
- 新增 schema DashboardMonitor Model 
- API
看程式碼就好
> feat: 更新 pin.value 變成不允許空值, 新增 Dashboard Monitor Model

- api/Dataservices/GroupDeviceDataservice.cs
- dashboard/src/components/empty-data-to-create-item/empty-data-to-create-item.tsx
- dashboard/src/components/header/header.tsx
- dashboard/src/components/pseudo-group-device-last-activity/pseudo-group-device-last-activity.tsx
- dashboard/src/constants/api.ts
- dashboard/src/hooks/apis/group-devices.hook.ts
- dashboard/src/index.tsx
- dashboard/src/pages/devices/devices.scss
- dashboard/src/pages/group-devices/group-devices.tsx
- dashboard/src/redux/reducers/group-devices.reducer.ts
- dashboard/src/redux/store.ts
- 實作群組裝置列表
看 Console Network 是否打的 API 為
`/groups/:groupId/devices` 
> Feat: group devices page

- api/Controllers/GroupDeviceController.cs
- api/Dataservices/GroupDataservice.cs
- 處理 group devices api 撈裝置列表的時候應該撈 建立群組關係的 Owner 不是 token 裡頭的 UserId
- API
> feat: bug 修正

- dashboard/src/app.tsx
- dashboard/src/components/header/header.tsx
- dashboard/src/constants/api.ts
- dashboard/src/constants/cookie-key.ts
- dashboard/src/helpers/api.helper.ts
- dashboard/src/hooks/apis/auth.hook.ts
- dashboard/src/hooks/apis/fetch.hook.ts
- dashboard/src/pages/groups/groups-join.tsx
- dashboard/src/types/helpers.type.ts
- website/src/controllers/two-factor-auth.controller.js
- refresh token 
- 加入群組後看是否可以直接切換群組，本來不行，因為舊的 token 裡頭沒有 group role
> feat: join group and refresh token

- api/Factories/PipelineFactory.cs
-  執行 delay 的紀錄，pipeline 擁有者和 pipeline id 錯置了
- API
- 建立一個 cronjob 排成
- 後面接著 delay pipeline 
- 執行完後到資料庫搜尋 PipelineExecuteLog 中 OwnerId 和 Pipeline Id 是否正確
> fix: 修正 execute pipeline delay log 參數錯誤

- api/Controllers/MyDashboardMonitorController.cs
- api/Controllers/MyDeviceController.cs
- api/Dataservices/DashboardMonitorDataservice.cs
- api/Dataservices/DeviceDataservice.cs
- api/Dataservices/GroupDeviceDataservice.cs
- as title
- API
- 刪掉 device 看對應的 monitor 是否還會出現
- 刪掉 group device 看對應的 monitor 是否也會消失在畫面上
> feat: 刪除 device 把相對應的資料跟著不顯示在畫面上，避免發生錯誤

- dashboard/src/components/custom-pipeline-item/check-last-online-pipeline-item.tsx
- dashboard/src/components/inputs/autocompleted-search/autocompleted-search.tsx
- dashboard/src/components/my-group-devices/my-group-devices.tsx
- as title
- 可以再新增完後繼續新增第二筆資料
- 優化群組裝置新增的表單
- #1339 
http://localhost:3000/dashboard/groups/{groupId}
新增完裝置後看會不會 Input 會不會清除可以，新增第二筆資料
> feat: 在 Autocomplete Search Component 加上 clearInputFlag 的 props

- website/src/controllers/smart-agriculture.controller.js
- website/src/template/smart-agriculture.html
- 文耕服務說明
- 表單選項新增水耕物聯網
- Ref: #1293
- Website F2E
> feat: 新增水耕服務說明

- api/Controllers/MyPipelineConnectorController.cs
- api/Controllers/MyPipelineItemController.cs
- 更新 API Document
- API
https://itemhub.io/swagger/index.html
把 `Pipeline 連線` 和 `Pipeline 單元` 拉到 `Pipeline` 裡頭
> feat: update document

- dashboard/src/app.tsx
- fix repeat call getGroupNames api 
- 看有沒有一直 call getGroupNames api 
> fix: get groupIds by reference

- api/Constants/ComputedTarget.cs
- api/Controllers/MyComputedFunctionController.cs
- api/Dataservices/ComputedFunctionDataservice.cs
- api/Migrations/20230811023235_AddComputedFunction.Designer.cs
- api/Migrations/20230811023235_AddComputedFunction.cs
- api/Migrations/20230811025250_UpdateComputedFunction.Designer.cs
- api/Migrations/20230811025250_UpdateComputedFunction.cs
- api/Migrations/20230811030657_UpdateComputedFunctionCreatedAtDefaultValue.Designer.cs
- api/Migrations/20230811030657_UpdateComputedFunctionCreatedAtDefaultValue.cs
- api/Models/DTOs/ComputedFunctionFilter.cs
- api/Models/DTOs/ContactUs.cs
- api/Models/EF/ComputedFunction.cs
- api/Models/EF/IotDbContext.cs
- dashboard/src/components/pin/pin.tsx
-  as subject
- API
- 新增測試資料 `INSERT INTO ComputedFunction (UserId, DeviceId, Pin, Func, Target) VALUES (Your User Id, Your Device Id, 'Your Pin', '(data) => { return data*2}', 0);
- 透過 POSTMAN 打以下 API `/api/v1/my/computed-functions?devicePins[0].deviceId=YourDeviceId&devicePins[0].pin=YourPin`
> 實作 computed function API

- website/src/template/checkout.html
> fix: 移除沒有在使用的 HTML

- website/src/components/header/header.html
- website/src/components/header/header.scss
- website/src/controllers/smart-agriculture.controller.js
- website/src/controllers/solution.controller.js
- website/src/css/overwrite.scss
- website/src/routing-rule.js
- website/src/swim/cacher.js
- website/src/template/solution.html
- Ref: #1344 
- Website F2E
- 確認網址名上 `?Type=basic` 、 `?Type=carbon` 可以 scroll 到對應內容，以及下方表單的選項有被勾選
- 確認資訊內容無誤
> feat: 增加輕量化的物聯網解決方案與智慧監測碳排放的解決方案

- dashboard/src/components/monitor-config-dialog/monitor-config-dialog.tsx
- dashboard/src/pages/dashboard/dashboard.tsx
- dashboard/src/redux/reducers/dashboard-monitor.reducer.ts
- 修正監控面板調整順序後沒有正常打 API 更新 #1372
- 修正監控面板重新自定義名稱後會消失 #1373 
- 更改 monitor 排序看一下會不會打 Patch API 並重新整理檢查排序是否還維持著
- 更改 monitor 自定義名稱，修改後檢查 dashboard 上面是否有 監控面板消失
> fix: 修正 dashboard monitor

- api/Controllers/MyPipelineExecuteLogController.cs
- api/Dataservices/PipelineExecuteLogDataservice.cs
- as subject
- API
測試以下 API 是否可以正常運作
http://localhost:5000/api/v1/pipelines/{id}/exeucte-logs?page=1&limit=10
加上 Query String 檢查資料是否在過濾範圍內
http://localhost:5000/api/v1/pipelines/{id}/exeucte-logs?page=1&limit=10&startAt=2022-10-01T00:00:00
http://localhost:5000/api/v1/pipelines/{id}/exeucte-logs?page=1&limit=10&endAt=2023-12-31T00:00:00
> feat: 實作 pipeline execute logs 分頁 API

- api/Controllers/MyPipelineExecuteLogController.cs
- api/Dataservices/PipelineExecuteLogDataservice.cs
- #1382 
- API
看code 就好 上 production 比較好測出來
> fix: 嘗試修正 pipeline execute log

- api/Dataservices/PipelineExecuteLogDataservice.cs
- dashboard/src/components/pipeline-execute-log-dialog/pipeline-execute-log-dialog.tsx
- dashboard/src/pages/pipelines/pipelines.tsx
- website/package-lock.json
- website/package.json
- 實作 pagination pipeline execute logs
- API
[https:](http://localhost:3000/dashboard/pipelines)
> feat: implement pipeline execute logs pagination

- dashboard/src/components/pipeline-execute-log-dialog/pipeline-execute-log-dialog.tsx
> fix: 關掉 pipeline execute dialog 的時後把所有 state 切到初始狀態

- api/Homo.AuthApi/Constants/AppSettings.cs
- api/Homo.AuthApi/Controllers/AuthResetPasswordController.cs
- api/Homo.AuthApi/Controllers/AuthSignInController.cs
- api/Homo.AuthApi/Controllers/AuthSignUpController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyEmailController.cs
- api/Homo.AuthApi/Controllers/AuthVerifyPhoneController.cs
- website/src/constants.js
- website/src/controllers/oauth.controller.js
- website/src/controllers/sign-up.controller.js
- website/src/controllers/verify-email.controller.js
- website/src/dataservices/auth.dataservice.js
- website/src/routing-rules/auth.routing-rule.js
- website/src/template/sign-up.html
> feat: 實作註冊時移除手機驗證
